// Code generated by simplexgen; DO NOT EDIT.

package command

import (
	"encoding/json"
	"fmt"

	"github.com/dop251/goja"
)

type APICreateMyAddress struct {
	UserId int64 `json:"userId"`
}

func (c APICreateMyAddress) CommandString() string {
	return evalJSCommandExpression(`'/_address ' + self.userId`, c)
}

type APIDeleteMyAddress struct {
	UserId int64 `json:"userId"`
}

func (c APIDeleteMyAddress) CommandString() string {
	return evalJSCommandExpression(`'/_delete_address ' + self.userId`, c)
}

type APIShowMyAddress struct {
	UserId int64 `json:"userId"`
}

func (c APIShowMyAddress) CommandString() string {
	return evalJSCommandExpression(`'/_show_address ' + self.userId`, c)
}

type APISetProfileAddress struct {
	UserId int64 `json:"userId"`
	Enable bool  `json:"enable"`
}

func (c APISetProfileAddress) CommandString() string {
	return evalJSCommandExpression(`'/_profile_address ' + self.userId + ' ' + (self.enable ? 'on' : 'off')`, c)
}

type APISetAddressSettings struct {
	UserId   int64          `json:"userId"`
	Settings map[string]any `json:"settings"`
}

func (c APISetAddressSettings) CommandString() string {
	return evalJSCommandExpression(`'/_address_settings ' + self.userId + ' ' + JSON.stringify(self.settings)`, c)
}

type APISendMessages struct {
	SendRef          string           `json:"sendRef"`
	LiveMessage      bool             `json:"liveMessage"`
	Ttl              *int64           `json:"ttl"`
	ComposedMessages []map[string]any `json:"composedMessages"`
}

func (c APISendMessages) CommandString() string {
	return evalJSCommandExpression(`'/_send ' + self.sendRef.toString() + (self.liveMessage ? ' live=on' : '') + (self.ttl ? ' ttl=' + self.ttl : '') + ' json ' + JSON.stringify(self.composedMessages)`, c)
}

type APIUpdateChatItem struct {
	ChatRef        string         `json:"chatRef"`
	ChatItemId     int64          `json:"chatItemId"`
	LiveMessage    bool           `json:"liveMessage"`
	UpdatedMessage map[string]any `json:"updatedMessage"`
}

func (c APIUpdateChatItem) CommandString() string {
	return evalJSCommandExpression(`'/_update item ' + self.chatRef.toString() + ' ' + self.chatItemId + (self.liveMessage ? ' live=on' : '') + ' json ' + JSON.stringify(self.updatedMessage)`, c)
}

type APIDeleteChatItem struct {
	ChatRef     string  `json:"chatRef"`
	ChatItemIds []int64 `json:"chatItemIds"`
	DeleteMode  string  `json:"deleteMode"`
}

func (c APIDeleteChatItem) CommandString() string {
	return evalJSCommandExpression(`'/_delete item ' + self.chatRef.toString() + ' ' + self.chatItemIds.join(',') + ' ' + self.deleteMode`, c)
}

type APIDeleteMemberChatItem struct {
	GroupId     int64   `json:"groupId"`
	ChatItemIds []int64 `json:"chatItemIds"`
}

func (c APIDeleteMemberChatItem) CommandString() string {
	return evalJSCommandExpression(`'/_delete member item #' + self.groupId + ' ' + self.chatItemIds.join(',')`, c)
}

type APIChatItemReaction struct {
	ChatRef    string         `json:"chatRef"`
	ChatItemId int64          `json:"chatItemId"`
	Add        bool           `json:"add"`
	Reaction   map[string]any `json:"reaction"`
}

func (c APIChatItemReaction) CommandString() string {
	return evalJSCommandExpression(`'/_reaction ' + self.chatRef.toString() + ' ' + self.chatItemId + ' ' + (self.add ? 'on' : 'off') + ' ' + JSON.stringify(self.reaction)`, c)
}

type ReceiveFile struct {
	FileId             int64   `json:"fileId"`
	UserApprovedRelays bool    `json:"userApprovedRelays"`
	StoreEncrypted     *bool   `json:"storeEncrypted"`
	FileInline         *bool   `json:"fileInline"`
	FilePath           *string `json:"filePath"`
}

func (c ReceiveFile) CommandString() string {
	return evalJSCommandExpression(`'/freceive ' + self.fileId + (self.userApprovedRelays ? ' approved_relays=on' : '') + (typeof self.storeEncrypted == 'boolean' ? ' encrypt=' + (self.storeEncrypted ? 'on' : 'off') : '') + (typeof self.fileInline == 'boolean' ? ' inline=' + (self.fileInline ? 'on' : 'off') : '') + (self.filePath ? ' ' + self.filePath : '')`, c)
}

type CancelFile struct {
	FileId int64 `json:"fileId"`
}

func (c CancelFile) CommandString() string {
	return evalJSCommandExpression(`'/fcancel ' + self.fileId`, c)
}

type APIAddMember struct {
	GroupId    int64  `json:"groupId"`
	ContactId  int64  `json:"contactId"`
	MemberRole string `json:"memberRole"`
}

func (c APIAddMember) CommandString() string {
	return evalJSCommandExpression(`'/_add #' + self.groupId + ' ' + self.contactId + ' ' + self.memberRole`, c)
}

type APIJoinGroup struct {
	GroupId int64 `json:"groupId"`
}

func (c APIJoinGroup) CommandString() string {
	return evalJSCommandExpression(`'/_join #' + self.groupId`, c)
}

type APIAcceptMember struct {
	GroupId       int64  `json:"groupId"`
	GroupMemberId int64  `json:"groupMemberId"`
	MemberRole    string `json:"memberRole"`
}

func (c APIAcceptMember) CommandString() string {
	return evalJSCommandExpression(`'/_accept member #' + self.groupId + ' ' + self.groupMemberId + ' ' + self.memberRole`, c)
}

type APIMembersRole struct {
	GroupId        int64   `json:"groupId"`
	GroupMemberIds []int64 `json:"groupMemberIds"`
	MemberRole     string  `json:"memberRole"`
}

func (c APIMembersRole) CommandString() string {
	return evalJSCommandExpression(`'/_member role #' + self.groupId + ' ' + self.groupMemberIds.join(',') + ' ' + self.memberRole`, c)
}

type APIBlockMembersForAll struct {
	GroupId        int64   `json:"groupId"`
	GroupMemberIds []int64 `json:"groupMemberIds"`
	Blocked        bool    `json:"blocked"`
}

func (c APIBlockMembersForAll) CommandString() string {
	return evalJSCommandExpression(`'/_block #' + self.groupId + ' ' + self.groupMemberIds.join(',') + ' blocked=' + (self.blocked ? 'on' : 'off')`, c)
}

type APIRemoveMembers struct {
	GroupId        int64   `json:"groupId"`
	GroupMemberIds []int64 `json:"groupMemberIds"`
	WithMessages   bool    `json:"withMessages"`
}

func (c APIRemoveMembers) CommandString() string {
	return evalJSCommandExpression(`'/_remove #' + self.groupId + ' ' + self.groupMemberIds.join(',') + (self.withMessages ? ' messages=on' : '')`, c)
}

type APILeaveGroup struct {
	GroupId int64 `json:"groupId"`
}

func (c APILeaveGroup) CommandString() string {
	return evalJSCommandExpression(`'/_leave #' + self.groupId`, c)
}

type APIListMembers struct {
	GroupId int64 `json:"groupId"`
}

func (c APIListMembers) CommandString() string {
	return evalJSCommandExpression(`'/_members #' + self.groupId`, c)
}

type APINewGroup struct {
	UserId       int64          `json:"userId"`
	Incognito    bool           `json:"incognito"`
	GroupProfile map[string]any `json:"groupProfile"`
}

func (c APINewGroup) CommandString() string {
	return evalJSCommandExpression(`'/_group ' + self.userId + (self.incognito ? ' incognito=on' : '') + ' ' + JSON.stringify(self.groupProfile)`, c)
}

type APIUpdateGroupProfile struct {
	GroupId      int64          `json:"groupId"`
	GroupProfile map[string]any `json:"groupProfile"`
}

func (c APIUpdateGroupProfile) CommandString() string {
	return evalJSCommandExpression(`'/_group_profile #' + self.groupId + ' ' + JSON.stringify(self.groupProfile)`, c)
}

type APICreateGroupLink struct {
	GroupId    int64  `json:"groupId"`
	MemberRole string `json:"memberRole"`
}

func (c APICreateGroupLink) CommandString() string {
	return evalJSCommandExpression(`'/_create link #' + self.groupId + ' ' + self.memberRole`, c)
}

type APIGroupLinkMemberRole struct {
	GroupId    int64  `json:"groupId"`
	MemberRole string `json:"memberRole"`
}

func (c APIGroupLinkMemberRole) CommandString() string {
	return evalJSCommandExpression(`'/_set link role #' + self.groupId + ' ' + self.memberRole`, c)
}

type APIDeleteGroupLink struct {
	GroupId int64 `json:"groupId"`
}

func (c APIDeleteGroupLink) CommandString() string {
	return evalJSCommandExpression(`'/_delete link #' + self.groupId`, c)
}

type APIGetGroupLink struct {
	GroupId int64 `json:"groupId"`
}

func (c APIGetGroupLink) CommandString() string {
	return evalJSCommandExpression(`'/_get link #' + self.groupId`, c)
}

type APIAddContact struct {
	UserId    int64 `json:"userId"`
	Incognito bool  `json:"incognito"`
}

func (c APIAddContact) CommandString() string {
	return evalJSCommandExpression(`'/_connect ' + self.userId + (self.incognito ? ' incognito=on' : '')`, c)
}

type APIConnectPlan struct {
	UserId         int64   `json:"userId"`
	ConnectionLink *string `json:"connectionLink"`
}

func (c APIConnectPlan) CommandString() string {
	return evalJSCommandExpression(`'/_connect plan ' + self.userId + ' ' + self.connectionLink`, c)
}

type APIConnect struct {
	UserId        int64   `json:"userId"`
	Incognito     bool    `json:"incognito"`
	PreparedLink_ *string `json:"preparedLink_"`
}

func (c APIConnect) CommandString() string {
	return evalJSCommandExpression(`'/_connect ' + self.userId + (self.preparedLink_ ? ' ' + self.preparedLink_.toString() : '')`, c)
}

type Connect struct {
	Incognito bool    `json:"incognito"`
	ConnLink_ *string `json:"connLink_"`
}

func (c Connect) CommandString() string {
	return evalJSCommandExpression(`'/connect' + (self.connLink_ ? ' ' + self.connLink_ : '')`, c)
}

type APIAcceptContact struct {
	ContactReqId int64 `json:"contactReqId"`
}

func (c APIAcceptContact) CommandString() string {
	return evalJSCommandExpression(`'/_accept ' + self.contactReqId`, c)
}

type APIRejectContact struct {
	ContactReqId int64 `json:"contactReqId"`
}

func (c APIRejectContact) CommandString() string {
	return evalJSCommandExpression(`'/_reject ' + self.contactReqId`, c)
}

type APIListContacts struct {
	UserId int64 `json:"userId"`
}

func (c APIListContacts) CommandString() string {
	return evalJSCommandExpression(`'/_contacts ' + self.userId`, c)
}

type APIListGroups struct {
	UserId     int64   `json:"userId"`
	ContactId_ *int64  `json:"contactId_"`
	Search     *string `json:"search"`
}

func (c APIListGroups) CommandString() string {
	return evalJSCommandExpression(`'/_groups ' + self.userId + (self.contactId_ ? ' @' + self.contactId_ : '') + (self.search ? ' ' + self.search : '')`, c)
}

type APIDeleteChat struct {
	ChatRef        string `json:"chatRef"`
	ChatDeleteMode string `json:"chatDeleteMode"`
}

func (c APIDeleteChat) CommandString() string {
	return evalJSCommandExpression(`'/_delete ' + self.chatRef.toString() + ' ' + self.chatDeleteMode.toString()`, c)
}

type ShowActiveUser struct {
}

func (c ShowActiveUser) CommandString() string {
	return evalJSCommandExpression(`'/user'`, c)
}

type CreateActiveUser struct {
	NewUser map[string]any `json:"newUser"`
}

func (c CreateActiveUser) CommandString() string {
	return evalJSCommandExpression(`'/_create user ' + JSON.stringify(self.newUser)`, c)
}

type ListUsers struct {
}

func (c ListUsers) CommandString() string {
	return evalJSCommandExpression(`'/users'`, c)
}

type APISetActiveUser struct {
	UserId  int64   `json:"userId"`
	ViewPwd *string `json:"viewPwd"`
}

func (c APISetActiveUser) CommandString() string {
	return evalJSCommandExpression(`'/_user ' + self.userId + (self.viewPwd ? ' ' + JSON.stringify(self.viewPwd) : '')`, c)
}

type APIDeleteUser struct {
	UserId       int64   `json:"userId"`
	DelSMPQueues bool    `json:"delSMPQueues"`
	ViewPwd      *string `json:"viewPwd"`
}

func (c APIDeleteUser) CommandString() string {
	return evalJSCommandExpression(`'/_delete user ' + self.userId + ' del_smp=' + (self.delSMPQueues ? 'on' : 'off') + (self.viewPwd ? ' ' + JSON.stringify(self.viewPwd) : '')`, c)
}

type APIUpdateProfile struct {
	UserId  int64          `json:"userId"`
	Profile map[string]any `json:"profile"`
}

func (c APIUpdateProfile) CommandString() string {
	return evalJSCommandExpression(`'/_profile ' + self.userId + ' ' + JSON.stringify(self.profile)`, c)
}

type APISetContactPrefs struct {
	ContactId   int64          `json:"contactId"`
	Preferences map[string]any `json:"preferences"`
}

func (c APISetContactPrefs) CommandString() string {
	return evalJSCommandExpression(`'/_set prefs @' + self.contactId + ' ' + JSON.stringify(self.preferences)`, c)
}

func evalJSCommandExpression(expr string, self any) string {
	payload, err := json.Marshal(self)
	if err != nil {
		panic(fmt.Sprintf("marshal command for expression eval: %v", err))
	}
	var m map[string]any
	if err := json.Unmarshal(payload, &m); err != nil {
		panic(fmt.Sprintf("unmarshal command payload for expression eval: %v", err))
	}
	vm := goja.New()
	if err := vm.Set("self", m); err != nil {
		panic(fmt.Sprintf("set self in expression VM: %v", err))
	}
	v, err := vm.RunString(expr)
	if err != nil {
		panic(fmt.Sprintf("evaluate command expression: %v", err))
	}
	return v.String()
}
