// Code generated by simplexgen; DO NOT EDIT.

package command

type APICreateMyAddress struct {
	UserId int64 `json:"userId"`
}

func (c APICreateMyAddress) CommandString() string {
	return "/_address " + jsToString(c.UserId)
}

type APIDeleteMyAddress struct {
	UserId int64 `json:"userId"`
}

func (c APIDeleteMyAddress) CommandString() string {
	return "/_delete_address " + jsToString(c.UserId)
}

type APIShowMyAddress struct {
	UserId int64 `json:"userId"`
}

func (c APIShowMyAddress) CommandString() string {
	return "/_show_address " + jsToString(c.UserId)
}

type APISetProfileAddress struct {
	UserId int64 `json:"userId"`
	Enable bool  `json:"enable"`
}

func (c APISetProfileAddress) CommandString() string {
	return "/_profile_address " + jsToString(c.UserId) + " " + ternaryString(jsTruthy(c.Enable), "on", "off")
}

type APISetAddressSettings struct {
	UserId   int64          `json:"userId"`
	Settings map[string]any `json:"settings"`
}

func (c APISetAddressSettings) CommandString() string {
	return "/_address_settings " + jsToString(c.UserId) + " " + mustJSON(c.Settings)
}

type APISendMessages struct {
	SendRef          string           `json:"sendRef"`
	LiveMessage      bool             `json:"liveMessage"`
	Ttl              *int64           `json:"ttl"`
	ComposedMessages []map[string]any `json:"composedMessages"`
}

func (c APISendMessages) CommandString() string {
	return "/_send " + jsToString(c.SendRef) + ternaryString(jsTruthy(c.LiveMessage), " live=on", "") + ternaryString(jsTruthy(c.Ttl), " ttl="+jsToString(c.Ttl), "") + " json " + mustJSON(c.ComposedMessages)
}

type APIUpdateChatItem struct {
	ChatRef        string         `json:"chatRef"`
	ChatItemId     int64          `json:"chatItemId"`
	LiveMessage    bool           `json:"liveMessage"`
	UpdatedMessage map[string]any `json:"updatedMessage"`
}

func (c APIUpdateChatItem) CommandString() string {
	return "/_update item " + jsToString(c.ChatRef) + " " + jsToString(c.ChatItemId) + ternaryString(jsTruthy(c.LiveMessage), " live=on", "") + " json " + mustJSON(c.UpdatedMessage)
}

type APIDeleteChatItem struct {
	ChatRef     string  `json:"chatRef"`
	ChatItemIds []int64 `json:"chatItemIds"`
	DeleteMode  string  `json:"deleteMode"`
}

func (c APIDeleteChatItem) CommandString() string {
	return "/_delete item " + jsToString(c.ChatRef) + " " + jsJoin(c.ChatItemIds, ",") + " " + jsToString(c.DeleteMode)
}

type APIDeleteMemberChatItem struct {
	GroupId     int64   `json:"groupId"`
	ChatItemIds []int64 `json:"chatItemIds"`
}

func (c APIDeleteMemberChatItem) CommandString() string {
	return "/_delete member item #" + jsToString(c.GroupId) + " " + jsJoin(c.ChatItemIds, ",")
}

type APIChatItemReaction struct {
	ChatRef    string         `json:"chatRef"`
	ChatItemId int64          `json:"chatItemId"`
	Add        bool           `json:"add"`
	Reaction   map[string]any `json:"reaction"`
}

func (c APIChatItemReaction) CommandString() string {
	return "/_reaction " + jsToString(c.ChatRef) + " " + jsToString(c.ChatItemId) + " " + ternaryString(jsTruthy(c.Add), "on", "off") + " " + mustJSON(c.Reaction)
}

type ReceiveFile struct {
	FileId             int64   `json:"fileId"`
	UserApprovedRelays bool    `json:"userApprovedRelays"`
	StoreEncrypted     *bool   `json:"storeEncrypted"`
	FileInline         *bool   `json:"fileInline"`
	FilePath           *string `json:"filePath"`
}

func (c ReceiveFile) CommandString() string {
	return "/freceive " + jsToString(c.FileId) + ternaryString(jsTruthy(c.UserApprovedRelays), " approved_relays=on", "") + ternaryString(jsLooseEqual(jsTypeOf(c.StoreEncrypted), "boolean"), " encrypt="+ternaryString(jsTruthy(c.StoreEncrypted), "on", "off"), "") + ternaryString(jsLooseEqual(jsTypeOf(c.FileInline), "boolean"), " inline="+ternaryString(jsTruthy(c.FileInline), "on", "off"), "") + ternaryString(jsTruthy(c.FilePath), " "+jsToString(c.FilePath), "")
}

type CancelFile struct {
	FileId int64 `json:"fileId"`
}

func (c CancelFile) CommandString() string {
	return "/fcancel " + jsToString(c.FileId)
}

type APIAddMember struct {
	GroupId    int64  `json:"groupId"`
	ContactId  int64  `json:"contactId"`
	MemberRole string `json:"memberRole"`
}

func (c APIAddMember) CommandString() string {
	return "/_add #" + jsToString(c.GroupId) + " " + jsToString(c.ContactId) + " " + jsToString(c.MemberRole)
}

type APIJoinGroup struct {
	GroupId int64 `json:"groupId"`
}

func (c APIJoinGroup) CommandString() string {
	return "/_join #" + jsToString(c.GroupId)
}

type APIAcceptMember struct {
	GroupId       int64  `json:"groupId"`
	GroupMemberId int64  `json:"groupMemberId"`
	MemberRole    string `json:"memberRole"`
}

func (c APIAcceptMember) CommandString() string {
	return "/_accept member #" + jsToString(c.GroupId) + " " + jsToString(c.GroupMemberId) + " " + jsToString(c.MemberRole)
}

type APIMembersRole struct {
	GroupId        int64   `json:"groupId"`
	GroupMemberIds []int64 `json:"groupMemberIds"`
	MemberRole     string  `json:"memberRole"`
}

func (c APIMembersRole) CommandString() string {
	return "/_member role #" + jsToString(c.GroupId) + " " + jsJoin(c.GroupMemberIds, ",") + " " + jsToString(c.MemberRole)
}

type APIBlockMembersForAll struct {
	GroupId        int64   `json:"groupId"`
	GroupMemberIds []int64 `json:"groupMemberIds"`
	Blocked        bool    `json:"blocked"`
}

func (c APIBlockMembersForAll) CommandString() string {
	return "/_block #" + jsToString(c.GroupId) + " " + jsJoin(c.GroupMemberIds, ",") + " blocked=" + ternaryString(jsTruthy(c.Blocked), "on", "off")
}

type APIRemoveMembers struct {
	GroupId        int64   `json:"groupId"`
	GroupMemberIds []int64 `json:"groupMemberIds"`
	WithMessages   bool    `json:"withMessages"`
}

func (c APIRemoveMembers) CommandString() string {
	return "/_remove #" + jsToString(c.GroupId) + " " + jsJoin(c.GroupMemberIds, ",") + ternaryString(jsTruthy(c.WithMessages), " messages=on", "")
}

type APILeaveGroup struct {
	GroupId int64 `json:"groupId"`
}

func (c APILeaveGroup) CommandString() string {
	return "/_leave #" + jsToString(c.GroupId)
}

type APIListMembers struct {
	GroupId int64 `json:"groupId"`
}

func (c APIListMembers) CommandString() string {
	return "/_members #" + jsToString(c.GroupId)
}

type APINewGroup struct {
	UserId       int64          `json:"userId"`
	Incognito    bool           `json:"incognito"`
	GroupProfile map[string]any `json:"groupProfile"`
}

func (c APINewGroup) CommandString() string {
	return "/_group " + jsToString(c.UserId) + ternaryString(jsTruthy(c.Incognito), " incognito=on", "") + " " + mustJSON(c.GroupProfile)
}

type APIUpdateGroupProfile struct {
	GroupId      int64          `json:"groupId"`
	GroupProfile map[string]any `json:"groupProfile"`
}

func (c APIUpdateGroupProfile) CommandString() string {
	return "/_group_profile #" + jsToString(c.GroupId) + " " + mustJSON(c.GroupProfile)
}

type APICreateGroupLink struct {
	GroupId    int64  `json:"groupId"`
	MemberRole string `json:"memberRole"`
}

func (c APICreateGroupLink) CommandString() string {
	return "/_create link #" + jsToString(c.GroupId) + " " + jsToString(c.MemberRole)
}

type APIGroupLinkMemberRole struct {
	GroupId    int64  `json:"groupId"`
	MemberRole string `json:"memberRole"`
}

func (c APIGroupLinkMemberRole) CommandString() string {
	return "/_set link role #" + jsToString(c.GroupId) + " " + jsToString(c.MemberRole)
}

type APIDeleteGroupLink struct {
	GroupId int64 `json:"groupId"`
}

func (c APIDeleteGroupLink) CommandString() string {
	return "/_delete link #" + jsToString(c.GroupId)
}

type APIGetGroupLink struct {
	GroupId int64 `json:"groupId"`
}

func (c APIGetGroupLink) CommandString() string {
	return "/_get link #" + jsToString(c.GroupId)
}

type APIAddContact struct {
	UserId    int64 `json:"userId"`
	Incognito bool  `json:"incognito"`
}

func (c APIAddContact) CommandString() string {
	return "/_connect " + jsToString(c.UserId) + ternaryString(jsTruthy(c.Incognito), " incognito=on", "")
}

type APIConnectPlan struct {
	UserId         int64   `json:"userId"`
	ConnectionLink *string `json:"connectionLink"`
}

func (c APIConnectPlan) CommandString() string {
	return "/_connect plan " + jsToString(c.UserId) + " " + jsToString(c.ConnectionLink)
}

type APIConnect struct {
	UserId        int64   `json:"userId"`
	Incognito     bool    `json:"incognito"`
	PreparedLink_ *string `json:"preparedLink_"`
}

func (c APIConnect) CommandString() string {
	return "/_connect " + jsToString(c.UserId) + ternaryString(jsTruthy(c.PreparedLink_), " "+jsToString(c.PreparedLink_), "")
}

type Connect struct {
	Incognito bool    `json:"incognito"`
	ConnLink_ *string `json:"connLink_"`
}

func (c Connect) CommandString() string {
	return "/connect" + ternaryString(jsTruthy(c.ConnLink_), " "+jsToString(c.ConnLink_), "")
}

type APIAcceptContact struct {
	ContactReqId int64 `json:"contactReqId"`
}

func (c APIAcceptContact) CommandString() string {
	return "/_accept " + jsToString(c.ContactReqId)
}

type APIRejectContact struct {
	ContactReqId int64 `json:"contactReqId"`
}

func (c APIRejectContact) CommandString() string {
	return "/_reject " + jsToString(c.ContactReqId)
}

type APIListContacts struct {
	UserId int64 `json:"userId"`
}

func (c APIListContacts) CommandString() string {
	return "/_contacts " + jsToString(c.UserId)
}

type APIListGroups struct {
	UserId     int64   `json:"userId"`
	ContactId_ *int64  `json:"contactId_"`
	Search     *string `json:"search"`
}

func (c APIListGroups) CommandString() string {
	return "/_groups " + jsToString(c.UserId) + ternaryString(jsTruthy(c.ContactId_), " @"+jsToString(c.ContactId_), "") + ternaryString(jsTruthy(c.Search), " "+jsToString(c.Search), "")
}

type APIDeleteChat struct {
	ChatRef        string `json:"chatRef"`
	ChatDeleteMode string `json:"chatDeleteMode"`
}

func (c APIDeleteChat) CommandString() string {
	return "/_delete " + jsToString(c.ChatRef) + " " + jsToString(c.ChatDeleteMode)
}

type ShowActiveUser struct {
}

func (c ShowActiveUser) CommandString() string {
	return "/user"
}

type CreateActiveUser struct {
	NewUser map[string]any `json:"newUser"`
}

func (c CreateActiveUser) CommandString() string {
	return "/_create user " + mustJSON(c.NewUser)
}

type ListUsers struct {
}

func (c ListUsers) CommandString() string {
	return "/users"
}

type APISetActiveUser struct {
	UserId  int64   `json:"userId"`
	ViewPwd *string `json:"viewPwd"`
}

func (c APISetActiveUser) CommandString() string {
	return "/_user " + jsToString(c.UserId) + ternaryString(jsTruthy(c.ViewPwd), " "+mustJSON(c.ViewPwd), "")
}

type APIDeleteUser struct {
	UserId       int64   `json:"userId"`
	DelSMPQueues bool    `json:"delSMPQueues"`
	ViewPwd      *string `json:"viewPwd"`
}

func (c APIDeleteUser) CommandString() string {
	return "/_delete user " + jsToString(c.UserId) + " del_smp=" + ternaryString(jsTruthy(c.DelSMPQueues), "on", "off") + ternaryString(jsTruthy(c.ViewPwd), " "+mustJSON(c.ViewPwd), "")
}

type APIUpdateProfile struct {
	UserId  int64          `json:"userId"`
	Profile map[string]any `json:"profile"`
}

func (c APIUpdateProfile) CommandString() string {
	return "/_profile " + jsToString(c.UserId) + " " + mustJSON(c.Profile)
}

type APISetContactPrefs struct {
	ContactId   int64          `json:"contactId"`
	Preferences map[string]any `json:"preferences"`
}

func (c APISetContactPrefs) CommandString() string {
	return "/_set prefs @" + jsToString(c.ContactId) + " " + mustJSON(c.Preferences)
}
