// Code generated by simplexgen; DO NOT EDIT.

package types

import "encoding/json"

type ACIReaction struct {
	ChatInfo     ChatInfo        `json:"chatInfo"`
	ChatReaction json.RawMessage `json:"chatReaction"`
}

type AChat struct {
	ChatInfo  ChatInfo        `json:"chatInfo"`
	ChatItems []ChatItem      `json:"chatItems"`
	ChatStats json.RawMessage `json:"chatStats"`
}

type ChatItemDeletion struct {
	DeletedChatItem AChatItem  `json:"deletedChatItem"`
	ToChatItem      *AChatItem `json:"toChatItem"`
}

type FileTransferMeta struct {
	FileId          int64           `json:"fileId"`
	XftpSndFile     json.RawMessage `json:"xftpSndFile"`
	XftpRedirectFor *int64          `json:"xftpRedirectFor"`
	FileName        string          `json:"fileName"`
	FilePath        string          `json:"filePath"`
	FileSize        int64           `json:"fileSize"`
	FileInline      json.RawMessage `json:"fileInline"`
	ChunkSize       int64           `json:"chunkSize"`
	Cancelled       bool            `json:"cancelled"`
}

type Group struct {
	GroupInfo GroupInfo     `json:"groupInfo"`
	Members   []GroupMember `json:"members"`
}

type GroupInfo struct {
	GroupId                 int64           `json:"groupId"`
	LocalDisplayName        string          `json:"localDisplayName"`
	GroupProfile            json.RawMessage `json:"groupProfile"`
	LocalAlias              string          `json:"localAlias"`
	BusinessChat            json.RawMessage `json:"businessChat"`
	FullGroupPreferences    json.RawMessage `json:"fullGroupPreferences"`
	Membership              GroupMember     `json:"membership"`
	ChatSettings            json.RawMessage `json:"chatSettings"`
	CreatedAt               string          `json:"createdAt"`
	UpdatedAt               string          `json:"updatedAt"`
	ChatTs                  *string         `json:"chatTs"`
	UserMemberProfileSentAt *string         `json:"userMemberProfileSentAt"`
	PreparedGroup           json.RawMessage `json:"preparedGroup"`
	ChatTags                []int64         `json:"chatTags"`
	ChatItemTTL             *int64          `json:"chatItemTTL"`
	UiThemes                json.RawMessage `json:"uiThemes"`
	CustomData              map[string]any  `json:"customData"`
	MembersRequireAttention int64           `json:"membersRequireAttention"`
	ViaGroupLinkUri         *string         `json:"viaGroupLinkUri"`
}

type GroupInfoSummary struct {
	GroupInfo    GroupInfo       `json:"groupInfo"`
	GroupSummary json.RawMessage `json:"groupSummary"`
}

type GroupLink struct {
	UserContactLinkId     int64           `json:"userContactLinkId"`
	ConnLinkContact       CreatedConnLink `json:"connLinkContact"`
	ShortLinkDataSet      bool            `json:"shortLinkDataSet"`
	ShortLinkLargeDataSet bool            `json:"shortLinkLargeDataSet"`
	GroupLinkId           string          `json:"groupLinkId"`
	AcceptMemberRole      json.RawMessage `json:"acceptMemberRole"`
}

type GroupMember struct {
	GroupMemberId          int64           `json:"groupMemberId"`
	GroupId                int64           `json:"groupId"`
	MemberId               string          `json:"memberId"`
	MemberRole             json.RawMessage `json:"memberRole"`
	MemberCategory         json.RawMessage `json:"memberCategory"`
	MemberStatus           json.RawMessage `json:"memberStatus"`
	MemberSettings         json.RawMessage `json:"memberSettings"`
	BlockedByAdmin         bool            `json:"blockedByAdmin"`
	InvitedBy              json.RawMessage `json:"invitedBy"`
	InvitedByGroupMemberId *int64          `json:"invitedByGroupMemberId"`
	LocalDisplayName       string          `json:"localDisplayName"`
	MemberProfile          json.RawMessage `json:"memberProfile"`
	MemberContactId        *int64          `json:"memberContactId"`
	MemberContactProfileId int64           `json:"memberContactProfileId"`
	ActiveConn             json.RawMessage `json:"activeConn"`
	MemberChatVRange       json.RawMessage `json:"memberChatVRange"`
	CreatedAt              string          `json:"createdAt"`
	UpdatedAt              string          `json:"updatedAt"`
	SupportChat            json.RawMessage `json:"supportChat"`
}

type PendingContactConnection struct {
	PccConnId           int64            `json:"pccConnId"`
	PccAgentConnId      string           `json:"pccAgentConnId"`
	PccConnStatus       json.RawMessage  `json:"pccConnStatus"`
	ViaContactUri       bool             `json:"viaContactUri"`
	ViaUserContactLink  *int64           `json:"viaUserContactLink"`
	GroupLinkId         *string          `json:"groupLinkId"`
	CustomUserProfileId *int64           `json:"customUserProfileId"`
	ConnLinkInv         *CreatedConnLink `json:"connLinkInv"`
	LocalAlias          string           `json:"localAlias"`
	CreatedAt           string           `json:"createdAt"`
	UpdatedAt           string           `json:"updatedAt"`
}

type RcvFileDescr struct {
	FileDescrId       int64  `json:"fileDescrId"`
	FileDescrText     string `json:"fileDescrText"`
	FileDescrPartNo   int64  `json:"fileDescrPartNo"`
	FileDescrComplete bool   `json:"fileDescrComplete"`
}

type RcvFileTransfer struct {
	FileId            int64           `json:"fileId"`
	XftpRcvFile       json.RawMessage `json:"xftpRcvFile"`
	FileInvitation    json.RawMessage `json:"fileInvitation"`
	FileStatus        json.RawMessage `json:"fileStatus"`
	RcvFileInline     json.RawMessage `json:"rcvFileInline"`
	SenderDisplayName string          `json:"senderDisplayName"`
	ChunkSize         int64           `json:"chunkSize"`
	Cancelled         bool            `json:"cancelled"`
	GrpMemberId       *int64          `json:"grpMemberId"`
	CryptoArgs        json.RawMessage `json:"cryptoArgs"`
}

type SndFileTransfer struct {
	FileId               int64           `json:"fileId"`
	FileName             string          `json:"fileName"`
	FilePath             string          `json:"filePath"`
	FileSize             int64           `json:"fileSize"`
	ChunkSize            int64           `json:"chunkSize"`
	RecipientDisplayName string          `json:"recipientDisplayName"`
	ConnId               int64           `json:"connId"`
	AgentConnId          string          `json:"agentConnId"`
	GroupMemberId        *int64          `json:"groupMemberId"`
	FileStatus           json.RawMessage `json:"fileStatus"`
	FileDescrId          *int64          `json:"fileDescrId"`
	FileInline           json.RawMessage `json:"fileInline"`
}

type UserContactRequest struct {
	ContactRequestId   int64           `json:"contactRequestId"`
	AgentInvitationId  string          `json:"agentInvitationId"`
	ContactId_         *int64          `json:"contactId_"`
	BusinessGroupId_   *int64          `json:"businessGroupId_"`
	UserContactLinkId_ *int64          `json:"userContactLinkId_"`
	CReqChatVRange     json.RawMessage `json:"cReqChatVRange"`
	LocalDisplayName   string          `json:"localDisplayName"`
	ProfileId          int64           `json:"profileId"`
	Profile            Profile         `json:"profile"`
	CreatedAt          string          `json:"createdAt"`
	UpdatedAt          string          `json:"updatedAt"`
	XContactId         *string         `json:"xContactId"`
	PqSupport          bool            `json:"pqSupport"`
	WelcomeSharedMsgId *string         `json:"welcomeSharedMsgId"`
	RequestSharedMsgId *string         `json:"requestSharedMsgId"`
}

type UserInfo struct {
	User        User  `json:"user"`
	UnreadCount int64 `json:"unreadCount"`
}

type UserProfileUpdateSummary struct {
	UpdateSuccesses int64     `json:"updateSuccesses"`
	UpdateFailures  int64     `json:"updateFailures"`
	ChangedContacts []Contact `json:"changedContacts"`
}
