// Code generated by simplexgen; DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
)

type ResponseAcceptingContactRequest struct {
	Type    ResponseType `json:"type"`
	User    User         `json:"user"`
	Contact Contact      `json:"contact"`
}

type ResponseActiveUser struct {
	Type ResponseType `json:"type"`
	User User         `json:"user"`
}

type ResponseChatItemNotChanged struct {
	Type     ResponseType `json:"type"`
	User     User         `json:"user"`
	ChatItem AChatItem    `json:"chatItem"`
}

type ResponseChatItemReaction struct {
	Type     ResponseType `json:"type"`
	User     User         `json:"user"`
	Added    bool         `json:"added"`
	Reaction ACIReaction  `json:"reaction"`
}

type ResponseChatItemUpdated struct {
	Type     ResponseType `json:"type"`
	User     User         `json:"user"`
	ChatItem AChatItem    `json:"chatItem"`
}

type ResponseChatItemsDeleted struct {
	Type              ResponseType       `json:"type"`
	User              User               `json:"user"`
	ChatItemDeletions []ChatItemDeletion `json:"chatItemDeletions"`
	ByUser            bool               `json:"byUser"`
	Timed             bool               `json:"timed"`
}

type ResponseCmdOk struct {
	Type  ResponseType `json:"type"`
	User_ *User        `json:"user_"`
}

type ResponseChatCmdError struct {
	Type      ResponseType `json:"type"`
	ChatError ChatError    `json:"chatError"`
}

type ResponseConnectionPlan struct {
	Type           ResponseType    `json:"type"`
	User           User            `json:"user"`
	ConnLink       CreatedConnLink `json:"connLink"`
	ConnectionPlan json.RawMessage `json:"connectionPlan"`
}

type ResponseContactAlreadyExists struct {
	Type    ResponseType `json:"type"`
	User    User         `json:"user"`
	Contact Contact      `json:"contact"`
}

type ResponseContactConnectionDeleted struct {
	Type       ResponseType             `json:"type"`
	User       User                     `json:"user"`
	Connection PendingContactConnection `json:"connection"`
}

type ResponseContactDeleted struct {
	Type    ResponseType `json:"type"`
	User    User         `json:"user"`
	Contact Contact      `json:"contact"`
}

type ResponseContactPrefsUpdated struct {
	Type        ResponseType `json:"type"`
	User        User         `json:"user"`
	FromContact Contact      `json:"fromContact"`
	ToContact   Contact      `json:"toContact"`
}

type ResponseContactRequestRejected struct {
	Type           ResponseType       `json:"type"`
	User           User               `json:"user"`
	ContactRequest UserContactRequest `json:"contactRequest"`
	Contact_       *Contact           `json:"contact_"`
}

type ResponseContactsList struct {
	Type     ResponseType `json:"type"`
	User     User         `json:"user"`
	Contacts []Contact    `json:"contacts"`
}

type ResponseGroupDeletedUser struct {
	Type      ResponseType `json:"type"`
	User      User         `json:"user"`
	GroupInfo GroupInfo    `json:"groupInfo"`
}

type ResponseGroupLink struct {
	Type      ResponseType `json:"type"`
	User      User         `json:"user"`
	GroupInfo GroupInfo    `json:"groupInfo"`
	GroupLink GroupLink    `json:"groupLink"`
}

type ResponseGroupLinkCreated struct {
	Type      ResponseType `json:"type"`
	User      User         `json:"user"`
	GroupInfo GroupInfo    `json:"groupInfo"`
	GroupLink GroupLink    `json:"groupLink"`
}

type ResponseGroupLinkDeleted struct {
	Type      ResponseType `json:"type"`
	User      User         `json:"user"`
	GroupInfo GroupInfo    `json:"groupInfo"`
}

type ResponseGroupCreated struct {
	Type      ResponseType `json:"type"`
	User      User         `json:"user"`
	GroupInfo GroupInfo    `json:"groupInfo"`
}

type ResponseGroupMembers struct {
	Type  ResponseType `json:"type"`
	User  User         `json:"user"`
	Group Group        `json:"group"`
}

type ResponseGroupUpdated struct {
	Type      ResponseType `json:"type"`
	User      User         `json:"user"`
	FromGroup GroupInfo    `json:"fromGroup"`
	ToGroup   GroupInfo    `json:"toGroup"`
	Member_   *GroupMember `json:"member_"`
}

type ResponseGroupsList struct {
	Type   ResponseType       `json:"type"`
	User   User               `json:"user"`
	Groups []GroupInfoSummary `json:"groups"`
}

type ResponseInvitation struct {
	Type               ResponseType             `json:"type"`
	User               User                     `json:"user"`
	ConnLinkInvitation CreatedConnLink          `json:"connLinkInvitation"`
	Connection         PendingContactConnection `json:"connection"`
}

type ResponseLeftMemberUser struct {
	Type      ResponseType `json:"type"`
	User      User         `json:"user"`
	GroupInfo GroupInfo    `json:"groupInfo"`
}

type ResponseMemberAccepted struct {
	Type      ResponseType `json:"type"`
	User      User         `json:"user"`
	GroupInfo GroupInfo    `json:"groupInfo"`
	Member    GroupMember  `json:"member"`
}

type ResponseMembersBlockedForAllUser struct {
	Type      ResponseType  `json:"type"`
	User      User          `json:"user"`
	GroupInfo GroupInfo     `json:"groupInfo"`
	Members   []GroupMember `json:"members"`
	Blocked   bool          `json:"blocked"`
}

type ResponseMembersRoleUser struct {
	Type      ResponseType    `json:"type"`
	User      User            `json:"user"`
	GroupInfo GroupInfo       `json:"groupInfo"`
	Members   []GroupMember   `json:"members"`
	ToRole    json.RawMessage `json:"toRole"`
}

type ResponseNewChatItems struct {
	Type      ResponseType `json:"type"`
	User      User         `json:"user"`
	ChatItems []AChatItem  `json:"chatItems"`
}

type ResponseRcvFileAccepted struct {
	Type     ResponseType `json:"type"`
	User     User         `json:"user"`
	ChatItem AChatItem    `json:"chatItem"`
}

type ResponseRcvFileAcceptedSndCancelled struct {
	Type            ResponseType    `json:"type"`
	User            User            `json:"user"`
	RcvFileTransfer RcvFileTransfer `json:"rcvFileTransfer"`
}

type ResponseRcvFileCancelled struct {
	Type            ResponseType    `json:"type"`
	User            User            `json:"user"`
	ChatItem_       *AChatItem      `json:"chatItem_"`
	RcvFileTransfer RcvFileTransfer `json:"rcvFileTransfer"`
}

type ResponseSentConfirmation struct {
	Type              ResponseType             `json:"type"`
	User              User                     `json:"user"`
	Connection        PendingContactConnection `json:"connection"`
	CustomUserProfile *Profile                 `json:"customUserProfile"`
}

type ResponseSentGroupInvitation struct {
	Type      ResponseType `json:"type"`
	User      User         `json:"user"`
	GroupInfo GroupInfo    `json:"groupInfo"`
	Contact   Contact      `json:"contact"`
	Member    GroupMember  `json:"member"`
}

type ResponseSentInvitation struct {
	Type              ResponseType             `json:"type"`
	User              User                     `json:"user"`
	Connection        PendingContactConnection `json:"connection"`
	CustomUserProfile *Profile                 `json:"customUserProfile"`
}

type ResponseSndFileCancelled struct {
	Type             ResponseType      `json:"type"`
	User             User              `json:"user"`
	ChatItem_        *AChatItem        `json:"chatItem_"`
	FileTransferMeta FileTransferMeta  `json:"fileTransferMeta"`
	SndFileTransfers []SndFileTransfer `json:"sndFileTransfers"`
}

type ResponseUserAcceptedGroupSent struct {
	Type        ResponseType `json:"type"`
	User        User         `json:"user"`
	GroupInfo   GroupInfo    `json:"groupInfo"`
	HostContact *Contact     `json:"hostContact"`
}

type ResponseUserContactLink struct {
	Type        ResponseType    `json:"type"`
	User        User            `json:"user"`
	ContactLink UserContactLink `json:"contactLink"`
}

type ResponseUserContactLinkCreated struct {
	Type            ResponseType    `json:"type"`
	User            User            `json:"user"`
	ConnLinkContact CreatedConnLink `json:"connLinkContact"`
}

type ResponseUserContactLinkDeleted struct {
	Type ResponseType `json:"type"`
	User User         `json:"user"`
}

type ResponseUserContactLinkUpdated struct {
	Type        ResponseType    `json:"type"`
	User        User            `json:"user"`
	ContactLink UserContactLink `json:"contactLink"`
}

type ResponseUserDeletedMembers struct {
	Type         ResponseType  `json:"type"`
	User         User          `json:"user"`
	GroupInfo    GroupInfo     `json:"groupInfo"`
	Members      []GroupMember `json:"members"`
	WithMessages bool          `json:"withMessages"`
}

type ResponseUserProfileUpdated struct {
	Type          ResponseType             `json:"type"`
	User          User                     `json:"user"`
	FromProfile   Profile                  `json:"fromProfile"`
	ToProfile     Profile                  `json:"toProfile"`
	UpdateSummary UserProfileUpdateSummary `json:"updateSummary"`
}

type ResponseUserProfileNoChange struct {
	Type ResponseType `json:"type"`
	User User         `json:"user"`
}

type ResponseUsersList struct {
	Type  ResponseType `json:"type"`
	Users []UserInfo   `json:"users"`
}

type EventContactConnected struct {
	Type              EventType `json:"type"`
	User              User      `json:"user"`
	Contact           Contact   `json:"contact"`
	UserCustomProfile *Profile  `json:"userCustomProfile"`
}

type EventContactUpdated struct {
	Type        EventType `json:"type"`
	User        User      `json:"user"`
	FromContact Contact   `json:"fromContact"`
	ToContact   Contact   `json:"toContact"`
}

type EventContactDeletedByContact struct {
	Type    EventType `json:"type"`
	User    User      `json:"user"`
	Contact Contact   `json:"contact"`
}

type EventReceivedContactRequest struct {
	Type           EventType          `json:"type"`
	User           User               `json:"user"`
	ContactRequest UserContactRequest `json:"contactRequest"`
	Chat_          *AChat             `json:"chat_"`
}

type EventNewMemberContactReceivedInv struct {
	Type      EventType   `json:"type"`
	User      User        `json:"user"`
	Contact   Contact     `json:"contact"`
	GroupInfo GroupInfo   `json:"groupInfo"`
	Member    GroupMember `json:"member"`
}

type EventContactSndReady struct {
	Type    EventType `json:"type"`
	User    User      `json:"user"`
	Contact Contact   `json:"contact"`
}

type EventNewChatItems struct {
	Type      EventType   `json:"type"`
	User      User        `json:"user"`
	ChatItems []AChatItem `json:"chatItems"`
}

type EventChatItemReaction struct {
	Type     EventType   `json:"type"`
	User     User        `json:"user"`
	Added    bool        `json:"added"`
	Reaction ACIReaction `json:"reaction"`
}

type EventChatItemsDeleted struct {
	Type              EventType          `json:"type"`
	User              User               `json:"user"`
	ChatItemDeletions []ChatItemDeletion `json:"chatItemDeletions"`
	ByUser            bool               `json:"byUser"`
	Timed             bool               `json:"timed"`
}

type EventChatItemUpdated struct {
	Type     EventType `json:"type"`
	User     User      `json:"user"`
	ChatItem AChatItem `json:"chatItem"`
}

type EventGroupChatItemsDeleted struct {
	Type        EventType    `json:"type"`
	User        User         `json:"user"`
	GroupInfo   GroupInfo    `json:"groupInfo"`
	ChatItemIDs []int64      `json:"chatItemIDs"`
	ByUser      bool         `json:"byUser"`
	Member_     *GroupMember `json:"member_"`
}

type EventChatItemsStatusesUpdated struct {
	Type      EventType   `json:"type"`
	User      User        `json:"user"`
	ChatItems []AChatItem `json:"chatItems"`
}

type EventReceivedGroupInvitation struct {
	Type           EventType       `json:"type"`
	User           User            `json:"user"`
	GroupInfo      GroupInfo       `json:"groupInfo"`
	Contact        Contact         `json:"contact"`
	FromMemberRole json.RawMessage `json:"fromMemberRole"`
	MemberRole     json.RawMessage `json:"memberRole"`
}

type EventUserJoinedGroup struct {
	Type       EventType   `json:"type"`
	User       User        `json:"user"`
	GroupInfo  GroupInfo   `json:"groupInfo"`
	HostMember GroupMember `json:"hostMember"`
}

type EventGroupUpdated struct {
	Type      EventType    `json:"type"`
	User      User         `json:"user"`
	FromGroup GroupInfo    `json:"fromGroup"`
	ToGroup   GroupInfo    `json:"toGroup"`
	Member_   *GroupMember `json:"member_"`
}

type EventJoinedGroupMember struct {
	Type      EventType   `json:"type"`
	User      User        `json:"user"`
	GroupInfo GroupInfo   `json:"groupInfo"`
	Member    GroupMember `json:"member"`
}

type EventMemberRole struct {
	Type      EventType       `json:"type"`
	User      User            `json:"user"`
	GroupInfo GroupInfo       `json:"groupInfo"`
	ByMember  GroupMember     `json:"byMember"`
	Member    GroupMember     `json:"member"`
	FromRole  json.RawMessage `json:"fromRole"`
	ToRole    json.RawMessage `json:"toRole"`
}

type EventDeletedMember struct {
	Type          EventType   `json:"type"`
	User          User        `json:"user"`
	GroupInfo     GroupInfo   `json:"groupInfo"`
	ByMember      GroupMember `json:"byMember"`
	DeletedMember GroupMember `json:"deletedMember"`
	WithMessages  bool        `json:"withMessages"`
}

type EventLeftMember struct {
	Type      EventType   `json:"type"`
	User      User        `json:"user"`
	GroupInfo GroupInfo   `json:"groupInfo"`
	Member    GroupMember `json:"member"`
}

type EventDeletedMemberUser struct {
	Type         EventType   `json:"type"`
	User         User        `json:"user"`
	GroupInfo    GroupInfo   `json:"groupInfo"`
	Member       GroupMember `json:"member"`
	WithMessages bool        `json:"withMessages"`
}

type EventGroupDeleted struct {
	Type      EventType   `json:"type"`
	User      User        `json:"user"`
	GroupInfo GroupInfo   `json:"groupInfo"`
	Member    GroupMember `json:"member"`
}

type EventConnectedToGroupMember struct {
	Type          EventType   `json:"type"`
	User          User        `json:"user"`
	GroupInfo     GroupInfo   `json:"groupInfo"`
	Member        GroupMember `json:"member"`
	MemberContact *Contact    `json:"memberContact"`
}

type EventMemberAcceptedByOther struct {
	Type            EventType   `json:"type"`
	User            User        `json:"user"`
	GroupInfo       GroupInfo   `json:"groupInfo"`
	AcceptingMember GroupMember `json:"acceptingMember"`
	Member          GroupMember `json:"member"`
}

type EventMemberBlockedForAll struct {
	Type      EventType   `json:"type"`
	User      User        `json:"user"`
	GroupInfo GroupInfo   `json:"groupInfo"`
	ByMember  GroupMember `json:"byMember"`
	Member    GroupMember `json:"member"`
	Blocked   bool        `json:"blocked"`
}

type EventGroupMemberUpdated struct {
	Type       EventType   `json:"type"`
	User       User        `json:"user"`
	GroupInfo  GroupInfo   `json:"groupInfo"`
	FromMember GroupMember `json:"fromMember"`
	ToMember   GroupMember `json:"toMember"`
}

type EventRcvFileDescrReady struct {
	Type            EventType       `json:"type"`
	User            User            `json:"user"`
	ChatItem        AChatItem       `json:"chatItem"`
	RcvFileTransfer RcvFileTransfer `json:"rcvFileTransfer"`
	RcvFileDescr    RcvFileDescr    `json:"rcvFileDescr"`
}

type EventRcvFileComplete struct {
	Type     EventType `json:"type"`
	User     User      `json:"user"`
	ChatItem AChatItem `json:"chatItem"`
}

type EventSndFileCompleteXFTP struct {
	Type             EventType        `json:"type"`
	User             User             `json:"user"`
	ChatItem         AChatItem        `json:"chatItem"`
	FileTransferMeta FileTransferMeta `json:"fileTransferMeta"`
}

type EventRcvFileStart struct {
	Type     EventType `json:"type"`
	User     User      `json:"user"`
	ChatItem AChatItem `json:"chatItem"`
}

type EventRcvFileSndCancelled struct {
	Type            EventType       `json:"type"`
	User            User            `json:"user"`
	ChatItem        AChatItem       `json:"chatItem"`
	RcvFileTransfer RcvFileTransfer `json:"rcvFileTransfer"`
}

type EventRcvFileAccepted struct {
	Type     EventType `json:"type"`
	User     User      `json:"user"`
	ChatItem AChatItem `json:"chatItem"`
}

type EventRcvFileError struct {
	Type            EventType       `json:"type"`
	User            User            `json:"user"`
	ChatItem_       *AChatItem      `json:"chatItem_"`
	AgentError      json.RawMessage `json:"agentError"`
	RcvFileTransfer RcvFileTransfer `json:"rcvFileTransfer"`
}

type EventRcvFileWarning struct {
	Type            EventType       `json:"type"`
	User            User            `json:"user"`
	ChatItem_       *AChatItem      `json:"chatItem_"`
	AgentError      json.RawMessage `json:"agentError"`
	RcvFileTransfer RcvFileTransfer `json:"rcvFileTransfer"`
}

type EventSndFileError struct {
	Type             EventType        `json:"type"`
	User             User             `json:"user"`
	ChatItem_        *AChatItem       `json:"chatItem_"`
	FileTransferMeta FileTransferMeta `json:"fileTransferMeta"`
	ErrorMessage     string           `json:"errorMessage"`
}

type EventSndFileWarning struct {
	Type             EventType        `json:"type"`
	User             User             `json:"user"`
	ChatItem_        *AChatItem       `json:"chatItem_"`
	FileTransferMeta FileTransferMeta `json:"fileTransferMeta"`
	ErrorMessage     string           `json:"errorMessage"`
}

type EventAcceptingContactRequest struct {
	Type    EventType `json:"type"`
	User    User      `json:"user"`
	Contact Contact   `json:"contact"`
}

type EventAcceptingBusinessRequest struct {
	Type      EventType `json:"type"`
	User      User      `json:"user"`
	GroupInfo GroupInfo `json:"groupInfo"`
}

type EventContactConnecting struct {
	Type    EventType `json:"type"`
	User    User      `json:"user"`
	Contact Contact   `json:"contact"`
}

type EventBusinessLinkConnecting struct {
	Type        EventType   `json:"type"`
	User        User        `json:"user"`
	GroupInfo   GroupInfo   `json:"groupInfo"`
	HostMember  GroupMember `json:"hostMember"`
	FromContact Contact     `json:"fromContact"`
}

type EventJoinedGroupMemberConnecting struct {
	Type       EventType   `json:"type"`
	User       User        `json:"user"`
	GroupInfo  GroupInfo   `json:"groupInfo"`
	HostMember GroupMember `json:"hostMember"`
	Member     GroupMember `json:"member"`
}

type EventSentGroupInvitation struct {
	Type      EventType   `json:"type"`
	User      User        `json:"user"`
	GroupInfo GroupInfo   `json:"groupInfo"`
	Contact   Contact     `json:"contact"`
	Member    GroupMember `json:"member"`
}

type EventGroupLinkConnecting struct {
	Type       EventType   `json:"type"`
	User       User        `json:"user"`
	GroupInfo  GroupInfo   `json:"groupInfo"`
	HostMember GroupMember `json:"hostMember"`
}

type EventMessageError struct {
	Type         EventType `json:"type"`
	User         User      `json:"user"`
	Severity     string    `json:"severity"`
	ErrorMessage string    `json:"errorMessage"`
}

type EventChatError struct {
	Type      EventType `json:"type"`
	ChatError ChatError `json:"chatError"`
}

type EventChatErrors struct {
	Type       EventType   `json:"type"`
	ChatErrors []ChatError `json:"chatErrors"`
}

func DecodeResponseByType(typ ResponseType, payload []byte) (any, error) {
	switch typ {
	case ResponseTypeAcceptingContactRequest:
		var v ResponseAcceptingContactRequest
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeActiveUser:
		var v ResponseActiveUser
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeChatItemNotChanged:
		var v ResponseChatItemNotChanged
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeChatItemReaction:
		var v ResponseChatItemReaction
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeChatItemUpdated:
		var v ResponseChatItemUpdated
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeChatItemsDeleted:
		var v ResponseChatItemsDeleted
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeCmdOk:
		var v ResponseCmdOk
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeChatCmdError:
		var v ResponseChatCmdError
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeConnectionPlan:
		var v ResponseConnectionPlan
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeContactAlreadyExists:
		var v ResponseContactAlreadyExists
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeContactConnectionDeleted:
		var v ResponseContactConnectionDeleted
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeContactDeleted:
		var v ResponseContactDeleted
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeContactPrefsUpdated:
		var v ResponseContactPrefsUpdated
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeContactRequestRejected:
		var v ResponseContactRequestRejected
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeContactsList:
		var v ResponseContactsList
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeGroupDeletedUser:
		var v ResponseGroupDeletedUser
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeGroupLink:
		var v ResponseGroupLink
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeGroupLinkCreated:
		var v ResponseGroupLinkCreated
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeGroupLinkDeleted:
		var v ResponseGroupLinkDeleted
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeGroupCreated:
		var v ResponseGroupCreated
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeGroupMembers:
		var v ResponseGroupMembers
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeGroupUpdated:
		var v ResponseGroupUpdated
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeGroupsList:
		var v ResponseGroupsList
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeInvitation:
		var v ResponseInvitation
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeLeftMemberUser:
		var v ResponseLeftMemberUser
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeMemberAccepted:
		var v ResponseMemberAccepted
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeMembersBlockedForAllUser:
		var v ResponseMembersBlockedForAllUser
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeMembersRoleUser:
		var v ResponseMembersRoleUser
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeNewChatItems:
		var v ResponseNewChatItems
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeRcvFileAccepted:
		var v ResponseRcvFileAccepted
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeRcvFileAcceptedSndCancelled:
		var v ResponseRcvFileAcceptedSndCancelled
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeRcvFileCancelled:
		var v ResponseRcvFileCancelled
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeSentConfirmation:
		var v ResponseSentConfirmation
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeSentGroupInvitation:
		var v ResponseSentGroupInvitation
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeSentInvitation:
		var v ResponseSentInvitation
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeSndFileCancelled:
		var v ResponseSndFileCancelled
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeUserAcceptedGroupSent:
		var v ResponseUserAcceptedGroupSent
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeUserContactLink:
		var v ResponseUserContactLink
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeUserContactLinkCreated:
		var v ResponseUserContactLinkCreated
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeUserContactLinkDeleted:
		var v ResponseUserContactLinkDeleted
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeUserContactLinkUpdated:
		var v ResponseUserContactLinkUpdated
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeUserDeletedMembers:
		var v ResponseUserDeletedMembers
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeUserProfileUpdated:
		var v ResponseUserProfileUpdated
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeUserProfileNoChange:
		var v ResponseUserProfileNoChange
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case ResponseTypeUsersList:
		var v ResponseUsersList
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	default:
		return nil, fmt.Errorf("unknown response type: %s", typ)
	}
}

func DecodeEventByType(typ EventType, payload []byte) (any, error) {
	switch typ {
	case EventTypeContactConnected:
		var v EventContactConnected
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeContactUpdated:
		var v EventContactUpdated
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeContactDeletedByContact:
		var v EventContactDeletedByContact
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeReceivedContactRequest:
		var v EventReceivedContactRequest
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeNewMemberContactReceivedInv:
		var v EventNewMemberContactReceivedInv
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeContactSndReady:
		var v EventContactSndReady
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeNewChatItems:
		var v EventNewChatItems
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeChatItemReaction:
		var v EventChatItemReaction
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeChatItemsDeleted:
		var v EventChatItemsDeleted
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeChatItemUpdated:
		var v EventChatItemUpdated
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeGroupChatItemsDeleted:
		var v EventGroupChatItemsDeleted
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeChatItemsStatusesUpdated:
		var v EventChatItemsStatusesUpdated
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeReceivedGroupInvitation:
		var v EventReceivedGroupInvitation
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeUserJoinedGroup:
		var v EventUserJoinedGroup
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeGroupUpdated:
		var v EventGroupUpdated
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeJoinedGroupMember:
		var v EventJoinedGroupMember
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeMemberRole:
		var v EventMemberRole
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeDeletedMember:
		var v EventDeletedMember
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeLeftMember:
		var v EventLeftMember
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeDeletedMemberUser:
		var v EventDeletedMemberUser
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeGroupDeleted:
		var v EventGroupDeleted
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeConnectedToGroupMember:
		var v EventConnectedToGroupMember
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeMemberAcceptedByOther:
		var v EventMemberAcceptedByOther
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeMemberBlockedForAll:
		var v EventMemberBlockedForAll
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeGroupMemberUpdated:
		var v EventGroupMemberUpdated
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeRcvFileDescrReady:
		var v EventRcvFileDescrReady
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeRcvFileComplete:
		var v EventRcvFileComplete
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeSndFileCompleteXFTP:
		var v EventSndFileCompleteXFTP
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeRcvFileStart:
		var v EventRcvFileStart
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeRcvFileSndCancelled:
		var v EventRcvFileSndCancelled
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeRcvFileAccepted:
		var v EventRcvFileAccepted
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeRcvFileError:
		var v EventRcvFileError
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeRcvFileWarning:
		var v EventRcvFileWarning
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeSndFileError:
		var v EventSndFileError
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeSndFileWarning:
		var v EventSndFileWarning
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeAcceptingContactRequest:
		var v EventAcceptingContactRequest
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeAcceptingBusinessRequest:
		var v EventAcceptingBusinessRequest
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeContactConnecting:
		var v EventContactConnecting
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeBusinessLinkConnecting:
		var v EventBusinessLinkConnecting
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeJoinedGroupMemberConnecting:
		var v EventJoinedGroupMemberConnecting
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeSentGroupInvitation:
		var v EventSentGroupInvitation
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeGroupLinkConnecting:
		var v EventGroupLinkConnecting
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeMessageError:
		var v EventMessageError
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeChatError:
		var v EventChatError
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EventTypeChatErrors:
		var v EventChatErrors
		if err := json.Unmarshal(payload, &v); err != nil {
			return nil, err
		}
		return v, nil
	default:
		return nil, fmt.Errorf("unknown event type: %s", typ)
	}
}
