package spec

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"
)

func RenderCatalogGo(doc CommandsDoc, pkg string) ([]byte, error) {
	if pkg == "" {
		pkg = "command"
	}
	if len(doc.Categories) == 0 {
		return nil, fmt.Errorf("empty commands document")
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by simplexgen; DO NOT EDIT.\n\n")
	b.WriteString("package ")
	b.WriteString(pkg)
	b.WriteString("\n\n")

	b.WriteString("var GeneratedCatalog = []Definition{\n")
	for _, cat := range doc.Categories {
		for _, cmd := range cat.Commands {
			b.WriteString("\t{\n")
			b.WriteString("\t\tName: ")
			b.WriteString(strconv.Quote(cmd.Name))
			b.WriteString(",\n")
			b.WriteString("\t\tCategory: ")
			b.WriteString(strconv.Quote(cat.Name))
			b.WriteString(",\n")
			b.WriteString("\t\tDescription: ")
			b.WriteString(strconv.Quote(cmd.Description))
			b.WriteString(",\n")
			b.WriteString("\t\tNetworkUsage: ")
			b.WriteString(networkUsageConst(cmd.NetworkUsage))
			b.WriteString(",\n")
			b.WriteString("\t\tSyntax: ")
			b.WriteString(strconv.Quote(cmd.Syntax))
			b.WriteString(",\n")
			b.WriteString("\t\tParameters: []Parameter{")
			for i, p := range cmd.Params {
				if i > 0 {
					b.WriteString(", ")
				}
				b.WriteString("{Name: ")
				b.WriteString(strconv.Quote(p.Name))
				b.WriteString(", Type: ")
				b.WriteString(strconv.Quote(p.Type))
				b.WriteString("}")
			}
			b.WriteString("},\n")
			b.WriteString("\t},\n")
		}
	}
	b.WriteString("}\n")

	out, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return out, nil
}

func networkUsageConst(u NetworkUsage) string {
	switch u {
	case NetworkUsageNo:
		return "NetworkUsageNo"
	case NetworkUsageInteractive:
		return "NetworkUsageInteractive"
	case NetworkUsageBackground:
		return "NetworkUsageBackground"
	default:
		return "NetworkUsageUnknown"
	}
}
