package spec

import (
	"bytes"
	"fmt"
	"go/format"
)

func RenderClientSendersGo(pkg string, commands []TSCommand) ([]byte, error) {
	if pkg == "" {
		pkg = "client"
	}
	if len(commands) == 0 {
		return nil, fmt.Errorf("no commands to render")
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by simplexgen; DO NOT EDIT.\n\n")
	b.WriteString("package ")
	b.WriteString(pkg)
	b.WriteString("\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\n")
	b.WriteString("\t\"github.com/Malomalsky/go-simplex/sdk/command\"\n")
	b.WriteString("\t\"github.com/Malomalsky/go-simplex/sdk/protocol\"\n")
	b.WriteString("\t\"github.com/Malomalsky/go-simplex/sdk/types\"\n")
	b.WriteString(")\n\n")

	for _, cmd := range commands {
		if len(cmd.Responses) == 0 {
			return nil, fmt.Errorf("command %s has no response types", cmd.Name)
		}

		resultType := cmd.Name + "Result"
		b.WriteString("type ")
		b.WriteString(resultType)
		b.WriteString(" struct {\n")
		b.WriteString("\tMessage protocol.Message\n")
		for _, resp := range cmd.Responses {
			respName := exportFirst(resp.Name)
			b.WriteString("\t")
			b.WriteString(respName)
			b.WriteString(" *types.Response")
			b.WriteString(respName)
			b.WriteString("\n")
		}
		b.WriteString("}\n\n")

		b.WriteString("func (c *Client) Send")
		b.WriteString(cmd.Name)
		b.WriteString("(ctx context.Context, req command.")
		b.WriteString(cmd.Name)
		b.WriteString(") (")
		b.WriteString(resultType)
		b.WriteString(", error) {\n")
		b.WriteString("\tmsg, err := c.Send(ctx, req)\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString("\t\treturn ")
		b.WriteString(resultType)
		b.WriteString("{}, err\n")
		b.WriteString("\t}\n")
		b.WriteString("\tout := ")
		b.WriteString(resultType)
		b.WriteString("{Message: msg}\n")
		b.WriteString("\tswitch types.ResponseType(msg.Resp.Type) {\n")
		for _, resp := range cmd.Responses {
			respName := exportFirst(resp.Name)
			b.WriteString("\tcase types.ResponseType")
			b.WriteString(respName)
			b.WriteString(":\n")
			b.WriteString("\t\tvar v types.Response")
			b.WriteString(respName)
			b.WriteString("\n")
			b.WriteString("\t\tif err := msg.Resp.Decode(&v); err != nil {\n")
			b.WriteString("\t\t\treturn ")
			b.WriteString(resultType)
			b.WriteString("{}, err\n")
			b.WriteString("\t\t}\n")
			b.WriteString("\t\tout.")
			b.WriteString(respName)
			b.WriteString(" = &v\n")
		}
		b.WriteString("\tdefault:\n")
		b.WriteString("\t\treturn out, nil\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn out, nil\n")
		b.WriteString("}\n\n")
	}

	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated client senders: %w", err)
	}
	return src, nil
}
