package spec

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"
	"strings"
	"unicode"
)

func RenderCommandRequestsGo(pkg string, commands []TSCommand) ([]byte, error) {
	if pkg == "" {
		pkg = "command"
	}
	if len(commands) == 0 {
		return nil, fmt.Errorf("no commands to render")
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by simplexgen; DO NOT EDIT.\n\n")
	b.WriteString("package ")
	b.WriteString(pkg)
	b.WriteString("\n\n")

	for _, cmd := range commands {
		b.WriteString("type ")
		b.WriteString(cmd.Name)
		b.WriteString(" struct {\n")
		for _, f := range cmd.Fields {
			b.WriteString("\t")
			b.WriteString(goCmdFieldName(f.Name))
			b.WriteString(" ")
			b.WriteString(mapTSCommandType(f))
			b.WriteString(" `json:")
			b.WriteString(strconv.Quote(f.Name))
			b.WriteString("`\n")
		}
		b.WriteString("}\n\n")

		b.WriteString("func (c ")
		b.WriteString(cmd.Name)
		b.WriteString(") CommandString() string {\n")
		b.WriteString("\treturn evalCommandExpression(`")
		b.WriteString(cmd.ExprJS)
		b.WriteString("`, c)\n")
		b.WriteString("}\n\n")
	}

	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated requests: %w", err)
	}
	return src, nil
}

func mapTSCommandType(f TSField) string {
	t := strings.TrimSpace(f.TypeExpr)

	if strings.HasSuffix(t, "[]") {
		base := strings.TrimSpace(strings.TrimSuffix(t, "[]"))
		elem := mapTSCommandBase(base, f.Comment)
		if strings.HasPrefix(elem, "*") {
			elem = strings.TrimPrefix(elem, "*")
		}
		return "[]" + elem
	}

	base := mapTSCommandBase(t, f.Comment)
	if f.Optional && isPointerCandidate(base) {
		return "*" + base
	}
	return base
}

func mapTSCommandBase(tsType, comment string) string {
	switch tsType {
	case "string":
		return "string"
	case "boolean":
		return "bool"
	case "number":
		c := strings.ToLower(comment)
		if strings.Contains(c, "int") || strings.Contains(c, "word32") {
			return "int64"
		}
		return "float64"
	case "object":
		return "map[string]any"
	}

	switch tsType {
	case "T.ChatRef":
		return "string"
	case "T.ChatDeleteMode":
		return "string"
	case "T.CIDeleteMode":
		return "string"
	case "T.GroupMemberRole":
		return "string"
	case "T.MsgReaction":
		return "map[string]any"
	case "T.AddressSettings":
		return "map[string]any"
	case "T.ComposedMessage":
		return "map[string]any"
	case "T.UpdatedMessage":
		return "map[string]any"
	case "T.GroupProfile":
		return "map[string]any"
	case "T.NewUser":
		return "map[string]any"
	case "T.UserPwdHash":
		return "map[string]any"
	case "T.Preferences":
		return "map[string]any"
	case "T.CreatedConnLink":
		return "string"
	case "T.PreparedContact":
		return "string"
	}

	if strings.HasPrefix(tsType, "T.") {
		return "map[string]any"
	}
	if strings.Contains(tsType, "|") {
		return "string"
	}
	return "string"
}

func goCmdFieldName(name string) string {
	if name == "" {
		return "Field"
	}
	r := []rune(name)
	if unicode.IsDigit(r[0]) {
		return "Field" + string(r)
	}
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}
