package spec

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"
	"strings"
	"unicode"
)

func RenderTypesRecordsGo(pkg string, responseIfaces []TSInterface, eventIfaces []TSInterface) ([]byte, error) {
	if pkg == "" {
		pkg = "types"
	}
	if len(responseIfaces) == 0 && len(eventIfaces) == 0 {
		return nil, fmt.Errorf("no interfaces to render")
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by simplexgen; DO NOT EDIT.\n\n")
	b.WriteString("package ")
	b.WriteString(pkg)
	b.WriteString("\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString(")\n\n")

	writeStructs(&b, "Response", "ResponseType", responseIfaces)
	writeStructs(&b, "Event", "EventType", eventIfaces)
	writeDecodeHelpers(&b, responseIfaces, eventIfaces)

	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated records: %w", err)
	}
	return src, nil
}

func writeStructs(b *bytes.Buffer, prefix, typeFieldType string, ifaces []TSInterface) {
	for _, iface := range ifaces {
		b.WriteString("type ")
		b.WriteString(prefix)
		b.WriteString(exportFirst(iface.Name))
		b.WriteString(" struct {\n")
		for _, f := range iface.Fields {
			fieldName := goFieldName(f.Name)
			fieldType := mapTSType(f, typeFieldType)
			if f.Optional && isPointerCandidate(fieldType) {
				fieldType = "*" + fieldType
			}
			b.WriteString("\t")
			b.WriteString(fieldName)
			b.WriteString(" ")
			b.WriteString(fieldType)
			b.WriteString(" `json:")
			b.WriteString(strconv.Quote(f.Name))
			b.WriteString("`\n")
		}
		b.WriteString("}\n\n")
	}
}

func writeDecodeHelpers(b *bytes.Buffer, responses []TSInterface, events []TSInterface) {
	b.WriteString("func DecodeResponseByType(typ ResponseType, payload []byte) (any, error) {\n")
	b.WriteString("\tswitch typ {\n")
	for _, iface := range responses {
		b.WriteString("\tcase ResponseType")
		b.WriteString(exportFirst(iface.Name))
		b.WriteString(":\n")
		b.WriteString("\t\tvar v Response")
		b.WriteString(exportFirst(iface.Name))
		b.WriteString("\n")
		b.WriteString("\t\tif err := json.Unmarshal(payload, &v); err != nil { return nil, err }\n")
		b.WriteString("\t\treturn v, nil\n")
	}
	b.WriteString("\tdefault:\n")
	b.WriteString("\t\treturn nil, fmt.Errorf(\"unknown response type: %s\", typ)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	b.WriteString("func DecodeEventByType(typ EventType, payload []byte) (any, error) {\n")
	b.WriteString("\tswitch typ {\n")
	for _, iface := range events {
		b.WriteString("\tcase EventType")
		b.WriteString(exportFirst(iface.Name))
		b.WriteString(":\n")
		b.WriteString("\t\tvar v Event")
		b.WriteString(exportFirst(iface.Name))
		b.WriteString("\n")
		b.WriteString("\t\tif err := json.Unmarshal(payload, &v); err != nil { return nil, err }\n")
		b.WriteString("\t\treturn v, nil\n")
	}
	b.WriteString("\tdefault:\n")
	b.WriteString("\t\treturn nil, fmt.Errorf(\"unknown event type: %s\", typ)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")
}

func mapTSType(f TSField, typeFieldType string) string {
	if f.Name == "type" {
		return typeFieldType
	}
	t := strings.TrimSpace(f.TypeExpr)
	if strings.HasSuffix(t, "[]") {
		base := strings.TrimSpace(strings.TrimSuffix(t, "[]"))
		elem := mapTSBase(base, f.Comment)
		if strings.HasPrefix(elem, "*") {
			elem = strings.TrimPrefix(elem, "*")
		}
		return "[]" + elem
	}
	return mapTSBase(t, f.Comment)
}

func mapTSBase(tsType, comment string) string {
	switch tsType {
	case "string":
		return "string"
	case "boolean":
		return "bool"
	case "number":
		c := strings.ToLower(comment)
		if strings.Contains(c, "double") {
			return "float64"
		}
		if strings.Contains(c, "int") || strings.Contains(c, "word32") {
			return "int64"
		}
		return "float64"
	case "object":
		return "map[string]any"
	}

	switch tsType {
	case "T.User":
		return "User"
	case "T.UserContactLink":
		return "UserContactLink"
	case "T.CreatedConnLink":
		return "CreatedConnLink"
	case "T.ChatError":
		return "ChatError"
	case "T.AChatItem":
		return "AChatItem"
	case "T.Contact":
		return "Contact"
	}

	if strings.Contains(tsType, "|") {
		return "json.RawMessage"
	}
	if strings.HasPrefix(tsType, "T.") {
		return "json.RawMessage"
	}
	if strings.Contains(tsType, "{") || strings.Contains(tsType, "}") {
		return "json.RawMessage"
	}

	return "json.RawMessage"
}

func goFieldName(name string) string {
	if name == "" {
		return "Field"
	}
	r := []rune(name)
	if unicode.IsDigit(r[0]) {
		return "Field" + string(r)
	}
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}

func exportFirst(s string) string {
	if s == "" {
		return ""
	}
	r := []rune(s)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}

func isPointerCandidate(goType string) bool {
	if strings.HasPrefix(goType, "[]") {
		return false
	}
	if strings.HasPrefix(goType, "map[") {
		return false
	}
	if goType == "json.RawMessage" {
		return false
	}
	return true
}
