package spec

import (
	"bytes"
	"fmt"
	"go/format"
	"unicode"
)

func RenderTypesTagsGo(pkg string, responseTags []TaggedType, eventTags []TaggedType) ([]byte, error) {
	if pkg == "" {
		pkg = "types"
	}
	if len(responseTags) == 0 && len(eventTags) == 0 {
		return nil, fmt.Errorf("no tags to render")
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by simplexgen; DO NOT EDIT.\n\n")
	b.WriteString("package ")
	b.WriteString(pkg)
	b.WriteString("\n\n")

	b.WriteString("type ResponseType string\n\n")
	b.WriteString("const (\n")
	for _, t := range responseTags {
		b.WriteString("\tResponseType")
		b.WriteString(exportName(t.Name))
		b.WriteString(" ResponseType = ")
		b.WriteString(`"`)
		b.WriteString(t.Tag)
		b.WriteString(`"`)
		b.WriteString("\n")
	}
	b.WriteString(")\n\n")

	b.WriteString("type EventType string\n\n")
	b.WriteString("const (\n")
	for _, t := range eventTags {
		b.WriteString("\tEventType")
		b.WriteString(exportName(t.Name))
		b.WriteString(" EventType = ")
		b.WriteString(`"`)
		b.WriteString(t.Tag)
		b.WriteString(`"`)
		b.WriteString("\n")
	}
	b.WriteString(")\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated tags: %w", err)
	}
	return src, nil
}

func exportName(name string) string {
	if name == "" {
		return ""
	}
	runes := []rune(name)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}
