// Code generated by simplexgen; DO NOT EDIT.

package client

import (
	"context"

	"github.com/Malomalsky/go-simplex/sdk/command"
	"github.com/Malomalsky/go-simplex/sdk/protocol"
	"github.com/Malomalsky/go-simplex/sdk/types"
)

type APICreateMyAddressResult struct {
	Message                protocol.Message
	UserContactLinkCreated *types.ResponseUserContactLinkCreated
	ChatCmdError           *types.ResponseChatCmdError
}

func (c *Client) SendAPICreateMyAddress(ctx context.Context, req command.APICreateMyAddress) (APICreateMyAddressResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APICreateMyAddressResult{}, err
	}
	out := APICreateMyAddressResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeUserContactLinkCreated:
		var v types.ResponseUserContactLinkCreated
		if err := msg.Resp.Decode(&v); err != nil {
			return APICreateMyAddressResult{}, err
		}
		out.UserContactLinkCreated = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APICreateMyAddressResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APIDeleteMyAddressResult struct {
	Message                protocol.Message
	UserContactLinkDeleted *types.ResponseUserContactLinkDeleted
	ChatCmdError           *types.ResponseChatCmdError
}

func (c *Client) SendAPIDeleteMyAddress(ctx context.Context, req command.APIDeleteMyAddress) (APIDeleteMyAddressResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APIDeleteMyAddressResult{}, err
	}
	out := APIDeleteMyAddressResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeUserContactLinkDeleted:
		var v types.ResponseUserContactLinkDeleted
		if err := msg.Resp.Decode(&v); err != nil {
			return APIDeleteMyAddressResult{}, err
		}
		out.UserContactLinkDeleted = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APIDeleteMyAddressResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APIShowMyAddressResult struct {
	Message         protocol.Message
	UserContactLink *types.ResponseUserContactLink
	ChatCmdError    *types.ResponseChatCmdError
}

func (c *Client) SendAPIShowMyAddress(ctx context.Context, req command.APIShowMyAddress) (APIShowMyAddressResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APIShowMyAddressResult{}, err
	}
	out := APIShowMyAddressResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeUserContactLink:
		var v types.ResponseUserContactLink
		if err := msg.Resp.Decode(&v); err != nil {
			return APIShowMyAddressResult{}, err
		}
		out.UserContactLink = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APIShowMyAddressResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APISetProfileAddressResult struct {
	Message            protocol.Message
	UserProfileUpdated *types.ResponseUserProfileUpdated
	ChatCmdError       *types.ResponseChatCmdError
}

func (c *Client) SendAPISetProfileAddress(ctx context.Context, req command.APISetProfileAddress) (APISetProfileAddressResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APISetProfileAddressResult{}, err
	}
	out := APISetProfileAddressResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeUserProfileUpdated:
		var v types.ResponseUserProfileUpdated
		if err := msg.Resp.Decode(&v); err != nil {
			return APISetProfileAddressResult{}, err
		}
		out.UserProfileUpdated = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APISetProfileAddressResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APISetAddressSettingsResult struct {
	Message                protocol.Message
	UserContactLinkUpdated *types.ResponseUserContactLinkUpdated
	ChatCmdError           *types.ResponseChatCmdError
}

func (c *Client) SendAPISetAddressSettings(ctx context.Context, req command.APISetAddressSettings) (APISetAddressSettingsResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APISetAddressSettingsResult{}, err
	}
	out := APISetAddressSettingsResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeUserContactLinkUpdated:
		var v types.ResponseUserContactLinkUpdated
		if err := msg.Resp.Decode(&v); err != nil {
			return APISetAddressSettingsResult{}, err
		}
		out.UserContactLinkUpdated = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APISetAddressSettingsResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APISendMessagesResult struct {
	Message      protocol.Message
	NewChatItems *types.ResponseNewChatItems
	ChatCmdError *types.ResponseChatCmdError
}

func (c *Client) SendAPISendMessages(ctx context.Context, req command.APISendMessages) (APISendMessagesResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APISendMessagesResult{}, err
	}
	out := APISendMessagesResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeNewChatItems:
		var v types.ResponseNewChatItems
		if err := msg.Resp.Decode(&v); err != nil {
			return APISendMessagesResult{}, err
		}
		out.NewChatItems = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APISendMessagesResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APIUpdateChatItemResult struct {
	Message            protocol.Message
	ChatItemUpdated    *types.ResponseChatItemUpdated
	ChatItemNotChanged *types.ResponseChatItemNotChanged
	ChatCmdError       *types.ResponseChatCmdError
}

func (c *Client) SendAPIUpdateChatItem(ctx context.Context, req command.APIUpdateChatItem) (APIUpdateChatItemResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APIUpdateChatItemResult{}, err
	}
	out := APIUpdateChatItemResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeChatItemUpdated:
		var v types.ResponseChatItemUpdated
		if err := msg.Resp.Decode(&v); err != nil {
			return APIUpdateChatItemResult{}, err
		}
		out.ChatItemUpdated = &v
	case types.ResponseTypeChatItemNotChanged:
		var v types.ResponseChatItemNotChanged
		if err := msg.Resp.Decode(&v); err != nil {
			return APIUpdateChatItemResult{}, err
		}
		out.ChatItemNotChanged = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APIUpdateChatItemResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APIDeleteChatItemResult struct {
	Message          protocol.Message
	ChatItemsDeleted *types.ResponseChatItemsDeleted
	ChatCmdError     *types.ResponseChatCmdError
}

func (c *Client) SendAPIDeleteChatItem(ctx context.Context, req command.APIDeleteChatItem) (APIDeleteChatItemResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APIDeleteChatItemResult{}, err
	}
	out := APIDeleteChatItemResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeChatItemsDeleted:
		var v types.ResponseChatItemsDeleted
		if err := msg.Resp.Decode(&v); err != nil {
			return APIDeleteChatItemResult{}, err
		}
		out.ChatItemsDeleted = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APIDeleteChatItemResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APIDeleteMemberChatItemResult struct {
	Message          protocol.Message
	ChatItemsDeleted *types.ResponseChatItemsDeleted
	ChatCmdError     *types.ResponseChatCmdError
}

func (c *Client) SendAPIDeleteMemberChatItem(ctx context.Context, req command.APIDeleteMemberChatItem) (APIDeleteMemberChatItemResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APIDeleteMemberChatItemResult{}, err
	}
	out := APIDeleteMemberChatItemResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeChatItemsDeleted:
		var v types.ResponseChatItemsDeleted
		if err := msg.Resp.Decode(&v); err != nil {
			return APIDeleteMemberChatItemResult{}, err
		}
		out.ChatItemsDeleted = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APIDeleteMemberChatItemResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APIChatItemReactionResult struct {
	Message          protocol.Message
	ChatItemReaction *types.ResponseChatItemReaction
	ChatCmdError     *types.ResponseChatCmdError
}

func (c *Client) SendAPIChatItemReaction(ctx context.Context, req command.APIChatItemReaction) (APIChatItemReactionResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APIChatItemReactionResult{}, err
	}
	out := APIChatItemReactionResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeChatItemReaction:
		var v types.ResponseChatItemReaction
		if err := msg.Resp.Decode(&v); err != nil {
			return APIChatItemReactionResult{}, err
		}
		out.ChatItemReaction = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APIChatItemReactionResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type ReceiveFileResult struct {
	Message                     protocol.Message
	RcvFileAccepted             *types.ResponseRcvFileAccepted
	RcvFileAcceptedSndCancelled *types.ResponseRcvFileAcceptedSndCancelled
	ChatCmdError                *types.ResponseChatCmdError
}

func (c *Client) SendReceiveFile(ctx context.Context, req command.ReceiveFile) (ReceiveFileResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return ReceiveFileResult{}, err
	}
	out := ReceiveFileResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeRcvFileAccepted:
		var v types.ResponseRcvFileAccepted
		if err := msg.Resp.Decode(&v); err != nil {
			return ReceiveFileResult{}, err
		}
		out.RcvFileAccepted = &v
	case types.ResponseTypeRcvFileAcceptedSndCancelled:
		var v types.ResponseRcvFileAcceptedSndCancelled
		if err := msg.Resp.Decode(&v); err != nil {
			return ReceiveFileResult{}, err
		}
		out.RcvFileAcceptedSndCancelled = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return ReceiveFileResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type CancelFileResult struct {
	Message          protocol.Message
	SndFileCancelled *types.ResponseSndFileCancelled
	RcvFileCancelled *types.ResponseRcvFileCancelled
	ChatCmdError     *types.ResponseChatCmdError
}

func (c *Client) SendCancelFile(ctx context.Context, req command.CancelFile) (CancelFileResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return CancelFileResult{}, err
	}
	out := CancelFileResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeSndFileCancelled:
		var v types.ResponseSndFileCancelled
		if err := msg.Resp.Decode(&v); err != nil {
			return CancelFileResult{}, err
		}
		out.SndFileCancelled = &v
	case types.ResponseTypeRcvFileCancelled:
		var v types.ResponseRcvFileCancelled
		if err := msg.Resp.Decode(&v); err != nil {
			return CancelFileResult{}, err
		}
		out.RcvFileCancelled = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return CancelFileResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APIAddMemberResult struct {
	Message             protocol.Message
	SentGroupInvitation *types.ResponseSentGroupInvitation
	ChatCmdError        *types.ResponseChatCmdError
}

func (c *Client) SendAPIAddMember(ctx context.Context, req command.APIAddMember) (APIAddMemberResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APIAddMemberResult{}, err
	}
	out := APIAddMemberResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeSentGroupInvitation:
		var v types.ResponseSentGroupInvitation
		if err := msg.Resp.Decode(&v); err != nil {
			return APIAddMemberResult{}, err
		}
		out.SentGroupInvitation = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APIAddMemberResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APIJoinGroupResult struct {
	Message               protocol.Message
	UserAcceptedGroupSent *types.ResponseUserAcceptedGroupSent
	ChatCmdError          *types.ResponseChatCmdError
}

func (c *Client) SendAPIJoinGroup(ctx context.Context, req command.APIJoinGroup) (APIJoinGroupResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APIJoinGroupResult{}, err
	}
	out := APIJoinGroupResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeUserAcceptedGroupSent:
		var v types.ResponseUserAcceptedGroupSent
		if err := msg.Resp.Decode(&v); err != nil {
			return APIJoinGroupResult{}, err
		}
		out.UserAcceptedGroupSent = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APIJoinGroupResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APIAcceptMemberResult struct {
	Message        protocol.Message
	MemberAccepted *types.ResponseMemberAccepted
	ChatCmdError   *types.ResponseChatCmdError
}

func (c *Client) SendAPIAcceptMember(ctx context.Context, req command.APIAcceptMember) (APIAcceptMemberResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APIAcceptMemberResult{}, err
	}
	out := APIAcceptMemberResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeMemberAccepted:
		var v types.ResponseMemberAccepted
		if err := msg.Resp.Decode(&v); err != nil {
			return APIAcceptMemberResult{}, err
		}
		out.MemberAccepted = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APIAcceptMemberResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APIMembersRoleResult struct {
	Message         protocol.Message
	MembersRoleUser *types.ResponseMembersRoleUser
	ChatCmdError    *types.ResponseChatCmdError
}

func (c *Client) SendAPIMembersRole(ctx context.Context, req command.APIMembersRole) (APIMembersRoleResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APIMembersRoleResult{}, err
	}
	out := APIMembersRoleResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeMembersRoleUser:
		var v types.ResponseMembersRoleUser
		if err := msg.Resp.Decode(&v); err != nil {
			return APIMembersRoleResult{}, err
		}
		out.MembersRoleUser = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APIMembersRoleResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APIBlockMembersForAllResult struct {
	Message                  protocol.Message
	MembersBlockedForAllUser *types.ResponseMembersBlockedForAllUser
	ChatCmdError             *types.ResponseChatCmdError
}

func (c *Client) SendAPIBlockMembersForAll(ctx context.Context, req command.APIBlockMembersForAll) (APIBlockMembersForAllResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APIBlockMembersForAllResult{}, err
	}
	out := APIBlockMembersForAllResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeMembersBlockedForAllUser:
		var v types.ResponseMembersBlockedForAllUser
		if err := msg.Resp.Decode(&v); err != nil {
			return APIBlockMembersForAllResult{}, err
		}
		out.MembersBlockedForAllUser = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APIBlockMembersForAllResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APIRemoveMembersResult struct {
	Message            protocol.Message
	UserDeletedMembers *types.ResponseUserDeletedMembers
	ChatCmdError       *types.ResponseChatCmdError
}

func (c *Client) SendAPIRemoveMembers(ctx context.Context, req command.APIRemoveMembers) (APIRemoveMembersResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APIRemoveMembersResult{}, err
	}
	out := APIRemoveMembersResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeUserDeletedMembers:
		var v types.ResponseUserDeletedMembers
		if err := msg.Resp.Decode(&v); err != nil {
			return APIRemoveMembersResult{}, err
		}
		out.UserDeletedMembers = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APIRemoveMembersResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APILeaveGroupResult struct {
	Message        protocol.Message
	LeftMemberUser *types.ResponseLeftMemberUser
	ChatCmdError   *types.ResponseChatCmdError
}

func (c *Client) SendAPILeaveGroup(ctx context.Context, req command.APILeaveGroup) (APILeaveGroupResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APILeaveGroupResult{}, err
	}
	out := APILeaveGroupResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeLeftMemberUser:
		var v types.ResponseLeftMemberUser
		if err := msg.Resp.Decode(&v); err != nil {
			return APILeaveGroupResult{}, err
		}
		out.LeftMemberUser = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APILeaveGroupResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APIListMembersResult struct {
	Message      protocol.Message
	GroupMembers *types.ResponseGroupMembers
	ChatCmdError *types.ResponseChatCmdError
}

func (c *Client) SendAPIListMembers(ctx context.Context, req command.APIListMembers) (APIListMembersResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APIListMembersResult{}, err
	}
	out := APIListMembersResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeGroupMembers:
		var v types.ResponseGroupMembers
		if err := msg.Resp.Decode(&v); err != nil {
			return APIListMembersResult{}, err
		}
		out.GroupMembers = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APIListMembersResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APINewGroupResult struct {
	Message      protocol.Message
	GroupCreated *types.ResponseGroupCreated
	ChatCmdError *types.ResponseChatCmdError
}

func (c *Client) SendAPINewGroup(ctx context.Context, req command.APINewGroup) (APINewGroupResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APINewGroupResult{}, err
	}
	out := APINewGroupResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeGroupCreated:
		var v types.ResponseGroupCreated
		if err := msg.Resp.Decode(&v); err != nil {
			return APINewGroupResult{}, err
		}
		out.GroupCreated = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APINewGroupResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APIUpdateGroupProfileResult struct {
	Message      protocol.Message
	GroupUpdated *types.ResponseGroupUpdated
	ChatCmdError *types.ResponseChatCmdError
}

func (c *Client) SendAPIUpdateGroupProfile(ctx context.Context, req command.APIUpdateGroupProfile) (APIUpdateGroupProfileResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APIUpdateGroupProfileResult{}, err
	}
	out := APIUpdateGroupProfileResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeGroupUpdated:
		var v types.ResponseGroupUpdated
		if err := msg.Resp.Decode(&v); err != nil {
			return APIUpdateGroupProfileResult{}, err
		}
		out.GroupUpdated = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APIUpdateGroupProfileResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APICreateGroupLinkResult struct {
	Message          protocol.Message
	GroupLinkCreated *types.ResponseGroupLinkCreated
	ChatCmdError     *types.ResponseChatCmdError
}

func (c *Client) SendAPICreateGroupLink(ctx context.Context, req command.APICreateGroupLink) (APICreateGroupLinkResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APICreateGroupLinkResult{}, err
	}
	out := APICreateGroupLinkResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeGroupLinkCreated:
		var v types.ResponseGroupLinkCreated
		if err := msg.Resp.Decode(&v); err != nil {
			return APICreateGroupLinkResult{}, err
		}
		out.GroupLinkCreated = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APICreateGroupLinkResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APIGroupLinkMemberRoleResult struct {
	Message      protocol.Message
	GroupLink    *types.ResponseGroupLink
	ChatCmdError *types.ResponseChatCmdError
}

func (c *Client) SendAPIGroupLinkMemberRole(ctx context.Context, req command.APIGroupLinkMemberRole) (APIGroupLinkMemberRoleResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APIGroupLinkMemberRoleResult{}, err
	}
	out := APIGroupLinkMemberRoleResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeGroupLink:
		var v types.ResponseGroupLink
		if err := msg.Resp.Decode(&v); err != nil {
			return APIGroupLinkMemberRoleResult{}, err
		}
		out.GroupLink = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APIGroupLinkMemberRoleResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APIDeleteGroupLinkResult struct {
	Message          protocol.Message
	GroupLinkDeleted *types.ResponseGroupLinkDeleted
	ChatCmdError     *types.ResponseChatCmdError
}

func (c *Client) SendAPIDeleteGroupLink(ctx context.Context, req command.APIDeleteGroupLink) (APIDeleteGroupLinkResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APIDeleteGroupLinkResult{}, err
	}
	out := APIDeleteGroupLinkResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeGroupLinkDeleted:
		var v types.ResponseGroupLinkDeleted
		if err := msg.Resp.Decode(&v); err != nil {
			return APIDeleteGroupLinkResult{}, err
		}
		out.GroupLinkDeleted = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APIDeleteGroupLinkResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APIGetGroupLinkResult struct {
	Message      protocol.Message
	GroupLink    *types.ResponseGroupLink
	ChatCmdError *types.ResponseChatCmdError
}

func (c *Client) SendAPIGetGroupLink(ctx context.Context, req command.APIGetGroupLink) (APIGetGroupLinkResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APIGetGroupLinkResult{}, err
	}
	out := APIGetGroupLinkResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeGroupLink:
		var v types.ResponseGroupLink
		if err := msg.Resp.Decode(&v); err != nil {
			return APIGetGroupLinkResult{}, err
		}
		out.GroupLink = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APIGetGroupLinkResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APIAddContactResult struct {
	Message      protocol.Message
	Invitation   *types.ResponseInvitation
	ChatCmdError *types.ResponseChatCmdError
}

func (c *Client) SendAPIAddContact(ctx context.Context, req command.APIAddContact) (APIAddContactResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APIAddContactResult{}, err
	}
	out := APIAddContactResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeInvitation:
		var v types.ResponseInvitation
		if err := msg.Resp.Decode(&v); err != nil {
			return APIAddContactResult{}, err
		}
		out.Invitation = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APIAddContactResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APIConnectPlanResult struct {
	Message        protocol.Message
	ConnectionPlan *types.ResponseConnectionPlan
	ChatCmdError   *types.ResponseChatCmdError
}

func (c *Client) SendAPIConnectPlan(ctx context.Context, req command.APIConnectPlan) (APIConnectPlanResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APIConnectPlanResult{}, err
	}
	out := APIConnectPlanResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeConnectionPlan:
		var v types.ResponseConnectionPlan
		if err := msg.Resp.Decode(&v); err != nil {
			return APIConnectPlanResult{}, err
		}
		out.ConnectionPlan = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APIConnectPlanResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APIConnectResult struct {
	Message              protocol.Message
	SentConfirmation     *types.ResponseSentConfirmation
	ContactAlreadyExists *types.ResponseContactAlreadyExists
	SentInvitation       *types.ResponseSentInvitation
	ChatCmdError         *types.ResponseChatCmdError
}

func (c *Client) SendAPIConnect(ctx context.Context, req command.APIConnect) (APIConnectResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APIConnectResult{}, err
	}
	out := APIConnectResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeSentConfirmation:
		var v types.ResponseSentConfirmation
		if err := msg.Resp.Decode(&v); err != nil {
			return APIConnectResult{}, err
		}
		out.SentConfirmation = &v
	case types.ResponseTypeContactAlreadyExists:
		var v types.ResponseContactAlreadyExists
		if err := msg.Resp.Decode(&v); err != nil {
			return APIConnectResult{}, err
		}
		out.ContactAlreadyExists = &v
	case types.ResponseTypeSentInvitation:
		var v types.ResponseSentInvitation
		if err := msg.Resp.Decode(&v); err != nil {
			return APIConnectResult{}, err
		}
		out.SentInvitation = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APIConnectResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type ConnectResult struct {
	Message              protocol.Message
	SentConfirmation     *types.ResponseSentConfirmation
	ContactAlreadyExists *types.ResponseContactAlreadyExists
	SentInvitation       *types.ResponseSentInvitation
	ChatCmdError         *types.ResponseChatCmdError
}

func (c *Client) SendConnect(ctx context.Context, req command.Connect) (ConnectResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return ConnectResult{}, err
	}
	out := ConnectResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeSentConfirmation:
		var v types.ResponseSentConfirmation
		if err := msg.Resp.Decode(&v); err != nil {
			return ConnectResult{}, err
		}
		out.SentConfirmation = &v
	case types.ResponseTypeContactAlreadyExists:
		var v types.ResponseContactAlreadyExists
		if err := msg.Resp.Decode(&v); err != nil {
			return ConnectResult{}, err
		}
		out.ContactAlreadyExists = &v
	case types.ResponseTypeSentInvitation:
		var v types.ResponseSentInvitation
		if err := msg.Resp.Decode(&v); err != nil {
			return ConnectResult{}, err
		}
		out.SentInvitation = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return ConnectResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APIAcceptContactResult struct {
	Message                 protocol.Message
	AcceptingContactRequest *types.ResponseAcceptingContactRequest
	ChatCmdError            *types.ResponseChatCmdError
}

func (c *Client) SendAPIAcceptContact(ctx context.Context, req command.APIAcceptContact) (APIAcceptContactResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APIAcceptContactResult{}, err
	}
	out := APIAcceptContactResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeAcceptingContactRequest:
		var v types.ResponseAcceptingContactRequest
		if err := msg.Resp.Decode(&v); err != nil {
			return APIAcceptContactResult{}, err
		}
		out.AcceptingContactRequest = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APIAcceptContactResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APIRejectContactResult struct {
	Message                protocol.Message
	ContactRequestRejected *types.ResponseContactRequestRejected
	ChatCmdError           *types.ResponseChatCmdError
}

func (c *Client) SendAPIRejectContact(ctx context.Context, req command.APIRejectContact) (APIRejectContactResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APIRejectContactResult{}, err
	}
	out := APIRejectContactResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeContactRequestRejected:
		var v types.ResponseContactRequestRejected
		if err := msg.Resp.Decode(&v); err != nil {
			return APIRejectContactResult{}, err
		}
		out.ContactRequestRejected = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APIRejectContactResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APIListContactsResult struct {
	Message      protocol.Message
	ContactsList *types.ResponseContactsList
	ChatCmdError *types.ResponseChatCmdError
}

func (c *Client) SendAPIListContacts(ctx context.Context, req command.APIListContacts) (APIListContactsResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APIListContactsResult{}, err
	}
	out := APIListContactsResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeContactsList:
		var v types.ResponseContactsList
		if err := msg.Resp.Decode(&v); err != nil {
			return APIListContactsResult{}, err
		}
		out.ContactsList = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APIListContactsResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APIListGroupsResult struct {
	Message      protocol.Message
	GroupsList   *types.ResponseGroupsList
	ChatCmdError *types.ResponseChatCmdError
}

func (c *Client) SendAPIListGroups(ctx context.Context, req command.APIListGroups) (APIListGroupsResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APIListGroupsResult{}, err
	}
	out := APIListGroupsResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeGroupsList:
		var v types.ResponseGroupsList
		if err := msg.Resp.Decode(&v); err != nil {
			return APIListGroupsResult{}, err
		}
		out.GroupsList = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APIListGroupsResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APIDeleteChatResult struct {
	Message                  protocol.Message
	ContactDeleted           *types.ResponseContactDeleted
	ContactConnectionDeleted *types.ResponseContactConnectionDeleted
	GroupDeletedUser         *types.ResponseGroupDeletedUser
	ChatCmdError             *types.ResponseChatCmdError
}

func (c *Client) SendAPIDeleteChat(ctx context.Context, req command.APIDeleteChat) (APIDeleteChatResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APIDeleteChatResult{}, err
	}
	out := APIDeleteChatResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeContactDeleted:
		var v types.ResponseContactDeleted
		if err := msg.Resp.Decode(&v); err != nil {
			return APIDeleteChatResult{}, err
		}
		out.ContactDeleted = &v
	case types.ResponseTypeContactConnectionDeleted:
		var v types.ResponseContactConnectionDeleted
		if err := msg.Resp.Decode(&v); err != nil {
			return APIDeleteChatResult{}, err
		}
		out.ContactConnectionDeleted = &v
	case types.ResponseTypeGroupDeletedUser:
		var v types.ResponseGroupDeletedUser
		if err := msg.Resp.Decode(&v); err != nil {
			return APIDeleteChatResult{}, err
		}
		out.GroupDeletedUser = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APIDeleteChatResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type ShowActiveUserResult struct {
	Message      protocol.Message
	ActiveUser   *types.ResponseActiveUser
	ChatCmdError *types.ResponseChatCmdError
}

func (c *Client) SendShowActiveUser(ctx context.Context, req command.ShowActiveUser) (ShowActiveUserResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return ShowActiveUserResult{}, err
	}
	out := ShowActiveUserResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeActiveUser:
		var v types.ResponseActiveUser
		if err := msg.Resp.Decode(&v); err != nil {
			return ShowActiveUserResult{}, err
		}
		out.ActiveUser = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return ShowActiveUserResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type CreateActiveUserResult struct {
	Message      protocol.Message
	ActiveUser   *types.ResponseActiveUser
	ChatCmdError *types.ResponseChatCmdError
}

func (c *Client) SendCreateActiveUser(ctx context.Context, req command.CreateActiveUser) (CreateActiveUserResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return CreateActiveUserResult{}, err
	}
	out := CreateActiveUserResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeActiveUser:
		var v types.ResponseActiveUser
		if err := msg.Resp.Decode(&v); err != nil {
			return CreateActiveUserResult{}, err
		}
		out.ActiveUser = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return CreateActiveUserResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type ListUsersResult struct {
	Message      protocol.Message
	UsersList    *types.ResponseUsersList
	ChatCmdError *types.ResponseChatCmdError
}

func (c *Client) SendListUsers(ctx context.Context, req command.ListUsers) (ListUsersResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return ListUsersResult{}, err
	}
	out := ListUsersResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeUsersList:
		var v types.ResponseUsersList
		if err := msg.Resp.Decode(&v); err != nil {
			return ListUsersResult{}, err
		}
		out.UsersList = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return ListUsersResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APISetActiveUserResult struct {
	Message      protocol.Message
	ActiveUser   *types.ResponseActiveUser
	ChatCmdError *types.ResponseChatCmdError
}

func (c *Client) SendAPISetActiveUser(ctx context.Context, req command.APISetActiveUser) (APISetActiveUserResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APISetActiveUserResult{}, err
	}
	out := APISetActiveUserResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeActiveUser:
		var v types.ResponseActiveUser
		if err := msg.Resp.Decode(&v); err != nil {
			return APISetActiveUserResult{}, err
		}
		out.ActiveUser = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APISetActiveUserResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APIDeleteUserResult struct {
	Message      protocol.Message
	CmdOk        *types.ResponseCmdOk
	ChatCmdError *types.ResponseChatCmdError
}

func (c *Client) SendAPIDeleteUser(ctx context.Context, req command.APIDeleteUser) (APIDeleteUserResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APIDeleteUserResult{}, err
	}
	out := APIDeleteUserResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeCmdOk:
		var v types.ResponseCmdOk
		if err := msg.Resp.Decode(&v); err != nil {
			return APIDeleteUserResult{}, err
		}
		out.CmdOk = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APIDeleteUserResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APIUpdateProfileResult struct {
	Message             protocol.Message
	UserProfileUpdated  *types.ResponseUserProfileUpdated
	UserProfileNoChange *types.ResponseUserProfileNoChange
	ChatCmdError        *types.ResponseChatCmdError
}

func (c *Client) SendAPIUpdateProfile(ctx context.Context, req command.APIUpdateProfile) (APIUpdateProfileResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APIUpdateProfileResult{}, err
	}
	out := APIUpdateProfileResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeUserProfileUpdated:
		var v types.ResponseUserProfileUpdated
		if err := msg.Resp.Decode(&v); err != nil {
			return APIUpdateProfileResult{}, err
		}
		out.UserProfileUpdated = &v
	case types.ResponseTypeUserProfileNoChange:
		var v types.ResponseUserProfileNoChange
		if err := msg.Resp.Decode(&v); err != nil {
			return APIUpdateProfileResult{}, err
		}
		out.UserProfileNoChange = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APIUpdateProfileResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}

type APISetContactPrefsResult struct {
	Message             protocol.Message
	ContactPrefsUpdated *types.ResponseContactPrefsUpdated
	ChatCmdError        *types.ResponseChatCmdError
}

func (c *Client) SendAPISetContactPrefs(ctx context.Context, req command.APISetContactPrefs) (APISetContactPrefsResult, error) {
	msg, err := c.Send(ctx, req)
	if err != nil {
		return APISetContactPrefsResult{}, err
	}
	out := APISetContactPrefsResult{Message: msg}
	switch types.ResponseType(msg.Resp.Type) {
	case types.ResponseTypeContactPrefsUpdated:
		var v types.ResponseContactPrefsUpdated
		if err := msg.Resp.Decode(&v); err != nil {
			return APISetContactPrefsResult{}, err
		}
		out.ContactPrefsUpdated = &v
	case types.ResponseTypeChatCmdError:
		var v types.ResponseChatCmdError
		if err := msg.Resp.Decode(&v); err != nil {
			return APISetContactPrefsResult{}, err
		}
		out.ChatCmdError = &v
	default:
		return out, nil
	}
	return out, nil
}
